#!/usr/bin/env python3
"""
font_to_c.py — render ASCII 32–126 from a TTF and emit a C header.

Usage:
    python3 font_to_c.py Roboto.ttf 12 > Roboto.h

The font_size argument controls the rendered point size.  Cell height is
fixed to font_size * 1.5 so descenders don't clip.  Each glyph is rendered
at 4× that height for supersampling, then downsampled with LANCZOS to the
final cell height.  Cell width is per-glyph (proportional font support):
the advance width is measured from Pillow's getbbox(), rounded up, and
stored alongside the alpha mask so the C program can lay out text with
correct spacing.

Output array layout:
    font_<stem>[ascii_code]  →  glyph_t  { advance_w, mask[CELL_H][advance_w] }

Because each glyph has a different width the header uses a struct-of-arrays
with a flat byte buffer and an offset table so the C side can index cheaply.
"""

import sys
import math
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if len(sys.argv) != 3:
    print(f"Usage: {sys.argv[0]} <font.ttf> <font_size>", file=sys.stderr)
    sys.exit(1)

ttf_path   = sys.argv[1]
font_size  = int(sys.argv[2])
stem       = Path(ttf_path).stem.replace("-", "_").replace(" ", "_")

# ---------------------------------------------------------------------------
# Geometry
# ---------------------------------------------------------------------------

CELL_H     = int(font_size * 1.5)   # final glyph height in pixels
SUPERSAMPLE = 4                      # render at this multiple, then downsample

render_size = font_size  * SUPERSAMPLE
render_h    = CELL_H     * SUPERSAMPLE

ASCII_FIRST = 32
ASCII_LAST  = 126

# ---------------------------------------------------------------------------
# Load font at render resolution
# ---------------------------------------------------------------------------

try:
    font = ImageFont.truetype(ttf_path, render_size)
except OSError as e:
    print(f"ERROR: {e}", file=sys.stderr)
    sys.exit(1)

# ---------------------------------------------------------------------------
# Measure and render each glyph
# ---------------------------------------------------------------------------

def render_glyph(char: str):
    """
    Returns (advance_w_final, rows) where:
      advance_w_final  — glyph width in final (non-supersampled) pixels
      rows             — list of CELL_H lists, each of advance_w_final uint8 values
    """
    # Measure advance at render resolution.
    # getlength() gives the full advance width including side-bearings.
    advance_render = math.ceil(font.getlength(char))
    if advance_render < 1:
        advance_render = render_size // 2   # fallback for whitespace

    # Render white glyph on black background at supersample resolution
    img = Image.new("L", (advance_render, render_h), 0)
    draw = ImageDraw.Draw(img)
    draw.text((0, 0), char, font=font, fill=255)

    # Downsample to final size with LANCZOS
    advance_final = max(1, round(advance_render / SUPERSAMPLE))
    small = img.resize((advance_final, CELL_H), Image.LANCZOS)

    pixels = list(small.getdata())
    rows = [pixels[r * advance_final:(r + 1) * advance_final] for r in range(CELL_H)]
    return advance_final, rows


glyphs = {}   # ascii_code → (advance_w, rows)
for code in range(ASCII_FIRST, ASCII_LAST + 1):
    glyphs[code] = render_glyph(chr(code))

# ---------------------------------------------------------------------------
# Emit header
# ---------------------------------------------------------------------------

out = sys.stdout

out.write(f"/*\n")
out.write(f" * {stem}.h — auto-generated by font_to_c.py\n")
out.write(f" *\n")
out.write(f" * Source : {ttf_path}\n")
out.write(f" * Size   : {font_size}px  (rendered at {render_size}px, downsampled {SUPERSAMPLE}×)\n")
out.write(f" * Height : {CELL_H}px per glyph (all glyphs share the same height)\n")
out.write(f" * Width  : variable (proportional font)\n")
out.write(f" *\n")
out.write(f" * Each glyph is stored as a flat row-major uint8 alpha mask.\n")
out.write(f" * 0 = fully transparent, 255 = fully opaque foreground.\n")
out.write(f" *\n")
out.write(f" * Access pattern:\n")
out.write(f" *   const {stem}_glyph_t *g = &{stem}[ascii_code];\n")
out.write(f" *   g->advance_w          — pixels to advance the cursor after drawing\n")
out.write(f" *   g->mask[row * g->advance_w + col]  — alpha value\n")
out.write(f" */\n\n")

out.write(f"#pragma once\n\n")
out.write(f"#include <stdint.h>\n\n")
out.write(f"#define {stem.upper()}_CELL_H  {CELL_H}\n\n")

out.write(f"typedef struct {{\n")
out.write(f"    int      advance_w;  /* glyph width in pixels                    */\n")
out.write(f"    const uint8_t *mask; /* row-major alpha mask, advance_w * CELL_H bytes */\n")
out.write(f"}} {stem}_glyph_t;\n\n")

# Emit one flat mask array per glyph, then the lookup table
# Control characters (0–31) and DEL (127) get a zero-width dummy entry.

# Emit mask data for printable glyphs
for code in range(ASCII_FIRST, ASCII_LAST + 1):
    advance_w, rows = glyphs[code]
    flat = [str(v) for row in rows for v in row]
    out.write(f"/* U+{code:04X} advance_w={advance_w} */\n")
    out.write(f"static const uint8_t _{stem}_mask_{code}[] = {{\n")
    # 16 values per line for readability
    for i in range(0, len(flat), 16):
        out.write("    " + ", ".join(flat[i:i+16]) + ",\n")
    out.write(f"}};\n\n")

# Emit the lookup table
out.write(f"static const {stem}_glyph_t {stem}[128] = {{\n")
for code in range(128):
    if ASCII_FIRST <= code <= ASCII_LAST:
        advance_w, _ = glyphs[code]
        out.write(f"    [{code}] = {{ {advance_w}, _{stem}_mask_{code} }},  /* U+{code:04X} */\n")
    else:
        out.write(f"    [{code}] = {{ 0, 0 }},\n")
out.write(f"}};\n")
