[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
rustflags = ["-C", "target-feature=+crt-static"]

[alias]
build-sdl = "build --release --example demo --features sdl,bpp16"
build-fb32 = "build --release --example demo --features fb0,bpp32"
build-fb16 = "build --release --example demo --features fb0,bpp16 --target armv7-unknown-linux-gnueabihf"
