[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
rustflags = ["-C", "target-feature=+crt-static"]

[target.wasm32-unknown-emscripten]
rustflags = [
    "-C", "link-args=-sUSE_SDL=2 -sSINGLE_FILE -sASYNCIFY -sALLOW_MEMORY_GROWTH=1 -fno-exceptions --embed-file fonts",
]

[alias]
build-sdl  = "build --release --example demo --features sdl,bpp16"
build-fb32 = "build --release --example demo --features fb0,bpp32"
build-fb16 = "build --release --example demo --features fb0,bpp16 --target armv7-unknown-linux-gnueabihf"
build-web  = "build --release --example demo --features web,bpp16 --target wasm32-unknown-emscripten"
