[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
rustflags = ["-C", "target-feature=+crt-static"]

[alias]
build-fb0 = "build --release --example demo --features fb0 --target armv7-unknown-linux-gnueabihf"
build-sdl = "build --release --example demo --features sdl"
