[alias]
sdl = "build -p demo-sdl"
fb32 = "build --release -p demo-fb32"
arm = "build --release -p demo-arm --target armv7-unknown-linux-gnueabihf"
wasm = "build -p demo-wasm --target wasm32-unknown-emscripten"

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
rustflags = ["-C", "target-feature=+crt-static"]

[target.wasm32-unknown-emscripten]
rustflags = ["-C", "link-args=-sALLOW_MEMORY_GROWTH=1 -sASYNCIFY --embed-file imgrids/src/fonts@/fonts --js-library=backends/wasm/web.js"]
