-- demo.lua — imgrids feature tutorial
-- Transpile: lua scripts/layout.lua < examples/demo.lua > examples/app/ui.rs

screen = {
	width = 800,
	height = 480,
}

colors = {
	white = { 255, 255, 255 },
	black = { 0, 0, 0 },
	red = { 255, 0, 0 },
	green = { 0, 255, 0 },
	blue = { 0, 0, 255 },
	yellow = { 255, 255, 0 },
}

fonts = {
	roboto = { "fonts/RobotoMono-Regular.ttf", 32 },
	small = { "fonts/RobotoMono-Regular.ttf", 20 },
	vga = { "raster::font_vga16", 12 },
}

style = {
	normal = {
		font = fonts.roboto,
		fg = colors.white,
		bg = colors.black,
		margin = 0,
		pad = 10,
		border = { width = 1, color = colors.white },
	},
	focused = {
		border = { width = 10 },
	},
}

-- Reusable style tables
local s_title = { bg = {60, 60, 60}, fg = colors.white, font = fonts.small,
                  border = {width = 0}, pad = 0, margin = 0, pad_left = 10 }
local s_desc  = { bg = colors.black, fg = colors.white, font = fonts.small,
                  border = {width = 0}, pad = 4, margin = 0, pad_left = 10 }
local s_btn   = { bg = {30, 80, 180}, border = {width = 2, color = colors.white}, margin = 4 }
local s_gap   = { border = {width = 0} }

-- Navigation row: structure helper (not just style)
local function nav(prev, next)
   return {"row", size = 60,
      {style = s_gap},
      {"Prev", weight = 2, press = {"nav", prev}, style = s_btn},
      {style = s_gap},
      {style = s_gap},
      {"Next", weight = 2, press = {"nav", next}, style = s_btn},
      {style = s_gap},
   }
end

menus = {

   Hello = {"col",
      {"col layout",                                        size = 40, style = s_title},
      {"col stacks children vertically.\nEach child gets equal height.", size = 50, style = s_desc},
      nav("Alignment", "Rows"),
      {"First",  style = {bg = {60,  60,  120}}},
      {"Second", style = {bg = {60,  120, 60 }}},
      {"Third",  style = {bg = {120, 60,  60 }}},
   },

   Rows = {"col",
      {"row layout",                                        size = 40, style = s_title},
      {"row places children side by side.\n(equal width by default)", size = 50, style = s_desc},
      nav("Hello", "Cols"),
      {"row", "Left", "Center", "Right"},
      {"row", "A", "B", "C", "D"},
   },

   Cols = {"col",
      {"col + row nesting",                                 size = 40, style = s_title},
      {"col inside a row:\neach column stacks its own children.", size = 50, style = s_desc},
      nav("Rows", "Weighted"),
      {"row",
         {"col", "Col A top", "Col A mid", "Col A bot"},
         {"col", "Col B top", "Col B mid", "Col B bot"},
         {"col", "Col C top", "Col C mid", "Col C bot"},
      },
   },

   Weighted = {"col",
      {"weight=",                                           size = 40, style = s_title},
      {"weight= sets proportional space.\nDefault weight is 1.", size = 50, style = s_desc},
      nav("Cols", "Fixed"),
      {"row", "weight 1", {"weight 2", weight=2}, {"weight 3", weight=3}},
   },

   Fixed = {"col",
      {"size= (fixed)",                                     size = 40, style = s_title},
      {"size= gives a child a fixed pixel size.\nWeighted children share the rest.", size = 50, style = s_desc},
      nav("Weighted", "CellStyle"),
      {"size=70 (fixed)",     size = 70},
      {"weight=2 (weighted)", weight = 2},
   },

   CellStyle = {"col",
      {"style=",                                            size = 40, style = s_title},
      {"Each cell carries a style= table.\nReuse named tables to share style.", size = 50, style = s_desc},
      nav("Fixed", "Pad"),
      {"row",
         {"blue cell",  style = {bg = colors.blue,  fg = colors.white}},
         {"default"},
         {"red cell",   style = {bg = colors.red,   fg = colors.white}},
         {"green cell", style = {bg = colors.green, fg = colors.black}},
      },
   },

   Pad = {"col",
      {"pad=",                                              size = 40, style = s_title},
      {"pad= adds internal space.\npad_left/top/right/bottom: per-side.", size = 50, style = s_desc},
      nav("CellStyle", "Margin"),
      {"row",
         {"pad=5",        style = {pad = 5}},
         {"pad=15",       style = {pad = 15}},
         {"pad_left=30",  style = {pad_left = 30}},
      },
      {"row",
         {"pad_top=20",    style = {pad_top    = 20}},
         {"pad_right=20",  style = {pad_right  = 20}},
         {"pad_bottom=20", style = {pad_bottom = 20}},
      },
   },

   Margin = {"col",
      {"margin=",                                           size = 40, style = s_title},
      {"margin= shrinks a child from outside.\n(all four sides equally)", size = 50, style = s_desc},
      nav("Pad", "Borders"),
      {"row",
         "margin 0",
         {"margin 20", style = {margin = 20, bg = colors.blue}},
         {"margin 5",  style = {margin = 5,  bg = colors.green}},
      },
   },

   Borders = {"col",
      border = {width = 0},  -- reset so the demos below are unambiguous
      {"border=",                                           size = 40, style = s_title},
      {"border= draws a border.\nside= restricts to one edge.", size = 50, style = s_desc},
      nav("Margin", "Clickable"),
      {"row", "no border", "no border", "no border"},
      {"row",
         {"width=4\ncolor=green",  style = {border = {width = 4, color = colors.green}}},
         {"width=4\nside=\"top\"",   style = {border = {width = 4, side = "top"}}},
         {"width=4\nside=\"right\"", style = {border = {width = 4, side = "right"}}},
         {"width=0",               style = {border = {width = 0}}},
      },
      {"row", "no border", "no border", "no border"},
      {"width=3, color=yellow", style = {border = {width = 3, color = colors.yellow}}},
   },

   Clickable = {"col",
      {"press= callbacks",                                  size = 40, style = s_title},
      {"press={fn, args...} triggers\na Callbacks method on press.", size = 50, style = s_desc},
      nav("Borders", "Focusable"),
      {'press={"click"}',          press = {"click"}},
      {'press={"action","hello"}', press = {"action", "hello"}},
      {'press={"action","a","b"}', press = {"action", "a", "b"}},
   },

   Focusable = {"col",
      {"focusable=",                                        size = 40, style = s_title},
      {"Focused cell redraws with style.focused.\nDefault: focusable iff press= is set.", size = 50, style = s_desc},
      nav("Clickable", "Dynamic"),
      {"row",
         {"press=\nfocusable=true",  press = {"click"}, focusable = true },
         {"press=\nfocusable=false", press = {"click"}, focusable = false},
      },
      {"row",
         {"label\nfocusable=true",  focusable = true },
         {"label\nfocusable=false", focusable = false},
      },
      {"row",
         {"press=\n(default)",  press = {"click"}},
         {"label\n(default)"},
      },
   },

   Dynamic = {"col",
      {"dynamic labels",                                    size = 40, style = s_title},
      {"lbl= cells get values via update_changes().\nThey start blank; populate on first update.", size = 50, style = s_desc},
      nav("Focusable", "Progress"),
      {lbl = "parameter One"},
      {lbl = "parameter Two"},
   },

   Progress = {"col",
      {"progress bar",                                      size = 40, style = s_title},
      {'render="progress bar":\nlbl= value is a float in [0,1].', size = 50, style = s_desc},
      nav("Dynamic", "Complex"),
      {lbl = "parameter One", render = "progress bar", style={pad=0}},
      {lbl = "parameter Two", render = "progress bar",
       style = {fg = colors.green, bg = {40, 40, 40}}},
      {"row",
         {lbl = "parameter One", render = "progress bar",
          style = {fg = colors.blue, bg = {40, 40, 40}}},
         {lbl = "parameter One"},
      },
   },

   Complex = {"col",
      {"nested containers",                                 size = 40, style = s_title},
      {"Containers nest freely:\ncol in row, row in col...", size = 50, style = s_desc},
      nav("Progress", "Popup"),
      {"row",
         {"col", "Top-left", "Bottom-left"},
         {"col",
            {"row", "TR-A", "TR-B"},
            {"row", "BR-A", "BR-B", "BR-C"},
         },
      },
   },

   Popup = {"col",
      menu_size  = {math.floor(0.5 * screen.width), math.floor(0.7 * screen.height)},
      menu_align = {math.floor(0.5 * screen.width), math.floor(0.5 * screen.height)},
      menu_anchor = "center",
      {"popup / aligned",                                   size = 40, style = s_title},
      {"menu_size={w,h}: menu size in pixels.\nmenu_align={x,y}+menu_anchor=: position.", size = 50, style = s_desc},
      nav("Complex", "Alignment"),
   },

   Alignment = {"col",
      {"text alignment",                                    size = 40, style = s_title},
      {"align= positions text within its cell.\nleft (default), center, right.", size = 50, style = s_desc},
      nav("Popup", "Hello"),
      {"row",
         {"Left (default)"},
         {"Centered", align = "center"},
         {"Right aligned", align = "right"},
      },
      {"row",
         {"Left line 1\nLeft line 2"},
         {"Center line 1\nCenter line 2", align = "center"},
         {"Right line 1\nRight line 2", align = "right"},
      },
   },
}
