-- demo.lua — imgrids feature tutorial
-- Transpile: lua scripts/layout.lua < examples/demo.lua > examples/app/ui.rs

dofile("scripts/symbols.lua")

screen = {
	width = 800,
	height = 480,
}

colors = {
	white = { 255, 255, 255 },
	black = { 0, 0, 0 },
	red = { 255, 0, 0 },
	green = { 0, 255, 0 },
	blue = { 0, 0, 255 },
	yellow = { 255, 255, 0 },
}

-- Convert code point to UTF-8 string
local function utf8char(cp)
	if cp < 0x80 then return string.char(cp) end
	if cp < 0x800 then
		return string.char(0xC0 + math.floor(cp / 64), 0x80 + cp % 64)
	end
	return string.char(0xE0 + math.floor(cp / 4096),
	                   0x80 + math.floor(cp / 64) % 64,
	                   0x80 + cp % 64)
end

-- Extra code points for non-ASCII characters
local PLUS_MINUS = utf8char(0x00B1)  -- ±
local MICRO      = utf8char(0x00B5)  -- µ
local DEGREE     = utf8char(0x00B0)  -- °

fonts = {
	myriad_large = { "fonts/MyriadPro-Regular.ttf", 32 },
	myriad_small = { "fonts/MyriadPro-Regular.ttf", 20 },
	roboto_large = { "fonts/RobotoMono-Regular.ttf", 32 },
	roboto_small = { "fonts/RobotoMono-Regular.ttf", 20 },
	vga = { "raster::font_vga16", 12 },
	-- Font with fallback: MyriadPro primary, FontAwesome for icons
	myriad_icons = { {"fonts/MyriadPro-Regular.ttf", 32}, {"fonts/FontAwesome5.ttf", 32} },
	-- Font with extra code points (non-ASCII like ±, µ, °)
	myriad_extra = { "fonts/MyriadPro-Regular.ttf", 32, extra = {0x00B1, 0x00B5, 0x00B0} },
	-- Font chain with extra code points
	myriad_icons_extra = { {"fonts/MyriadPro-Regular.ttf", 32}, {"fonts/FontAwesome5.ttf", 32},
	                       extra = {0x00B1, 0x00B5, 0x00B0} },
}

style = {
	normal = {
		font = fonts.myriad_large,
		fg = colors.white,
		bg = colors.black,
		margin = 0,
		pad = 10,
		border = { width = 1, color = colors.white },
	},
	focused = {
		border = { width = 10 },
	},
}

-- Reusable style tables
local s_title = { bg = {60, 60, 60}, fg = colors.white, font = fonts.myriad_small,
                  border = {width = 0}, pad = 0, margin = 0, pad_left = 10 }
local s_desc  = { bg = colors.black, fg = colors.white, font = fonts.myriad_small,
                  border = {width = 0}, pad = 4, margin = 0, pad_left = 10 }
local s_btn   = { bg = {30, 80, 180}, border = {width = 2, color = colors.white}, margin = 4 }
local s_gap   = { border = {width = 0} }

-- Navigation row: structure helper (not just style)
local function nav(prev, next)
   return {"row", size = 60,
      {style = s_gap},
      {"Prev", weight = 2, press = {"nav", prev}, style = s_btn},
      {style = s_gap},
      {style = s_gap},
      {"Next", weight = 2, press = {"nav", next}, style = s_btn},
      {style = s_gap},
   }
end

menus = {

   Hello = {"col",
      {"[1/30] Col Layout",                                        size = 40, style = s_title},
      {"col stacks children vertically.\nEach child gets equal height.", size = 50, style = s_desc},
      nav("Popup", "Rows"),
      {"First",  style = {bg = {60,  60,  120}}},
      {"Second", style = {bg = {60,  120, 60 }}},
      {"Third",  style = {bg = {120, 60,  60 }}},
   },

   Rows = {"col",
      {"[2/30] Row Layout",                                        size = 40, style = s_title},
      {"row places children side by side.\n(equal width by default)", size = 50, style = s_desc},
      nav("Hello", "Cols"),
      {"row", "Left", "Center", "Right"},
      {"row", "A", "B", "C", "D"},
   },

   Cols = {"col",
      {"[3/30] Col + Row Nesting",                                 size = 40, style = s_title},
      {"col inside a row:\neach column stacks its own children.", size = 50, style = s_desc},
      nav("Rows", "Weighted"),
      {"row",
         {"col", "Col A top", "Col A mid", "Col A bot"},
         {"col", "Col B top", "Col B mid", "Col B bot"},
         {"col", "Col C top", "Col C mid", "Col C bot"},
      },
   },

   Weighted = {"col",
      {"[4/30] Proportional Weights",                               size = 40, style = s_title},
      {"weight= sets proportional space.\nDefault weight is 1.", size = 50, style = s_desc},
      nav("Cols", "Fixed"),
      {"row", "weight 1", {"weight 2", weight=2}, {"weight 3", weight=3}},
   },

   Fixed = {"col",
      {"[5/30] Fixed Sizes",                                       size = 40, style = s_title},
      {"size= gives a child a fixed pixel size.\nWeighted children share the rest.", size = 50, style = s_desc},
      nav("Weighted", "CellStyle"),
      {"size=70 (fixed)",     size = 70},
      {"weight=2 (weighted)", weight = 2},
   },

   CellStyle = {"col",
      {"[6/30] Cell Styling",                                      size = 40, style = s_title},
      {"Each cell carries a style= table.\nReuse named tables to share style.", size = 50, style = s_desc},
      nav("Fixed", "LeafStyle"),
      {"row",
         {"blue cell",  style = {bg = colors.blue,  fg = colors.white}},
         {"default"},
         {"red cell",   style = {bg = colors.red,   fg = colors.white}},
         {"green cell", style = {bg = colors.green, fg = colors.black}},
      },
   },

   LeafStyle = {"col",
      {"[7/30] Leaf Style",                                       size = 40, style = s_title},
      {"leaf_style= sets style for all leaves\nin a container. Per-node style= overrides.", size = 50, style = s_desc},
      nav("CellStyle", "ContainerBg"),
      {"row", leaf_style = {bg = {40, 40, 100}, fg = colors.white},
         {"col",
            {"row", "A1", "A2"},
            {"row", "A3", {"A4", style = {bg = colors.red}}},
         },
         {"col", leaf_style = {bg = {40, 100, 40}},
            {"row", "B1", "B2"},
            {"row", "B3", "B4"},
         },
         {"col",
            {"C1"},
            {"C2", style = {bg = colors.yellow, fg = colors.black}},
         },
      },
   },

   ContainerBg = {"col",
      {"[8/30] Container Background",                              size = 40, style = s_title},
      {"style={bg=...} on a container fills\nbehind all children.", size = 50, style = s_desc},
      nav("LeafStyle", "Pad"),
      {"row",
         {"col", style = {bg = {80, 40, 40}},
            {"Child 1"},
            {"Child 2"},
         },
         {"col", style = {bg = {40, 40, 80}},
            {"Child 3"},
            {"Child 4"},
         },
      },
   },

   Pad = {"col",
      {"[9/30] Padding",                                           size = 40, style = s_title},
      {"pad= adds internal space.\npad_left/top/right/bottom: per-side.", size = 50, style = s_desc},
      nav("ContainerBg", "Margin"),
      {"row",
         {"pad=5",        style = {pad = 5,        bg = {40, 40, 80}}},
         {"pad=15",       style = {pad = 15,       bg = {40, 40, 80}}},
         {"pad_left=30",  style = {pad_left = 30,  bg = {40, 40, 80}}},
      },
      {"row",
         {"pad_top=20",    style = {pad_top    = 20, bg = {40, 80, 40}}},
         {"pad_right=20",  style = {pad_right  = 20, bg = {40, 80, 40}}},
         {"pad_bottom=20", style = {pad_bottom = 20, bg = {40, 80, 40}}},
      },
   },

   Margin = {"col",
      {"[10/30] Margins",                                           size = 40, style = s_title},
      {"margin= shrinks from outside.\nmargin_left/top/right/bottom: per-side.", size = 50, style = s_desc},
      nav("Pad", "FlushCells"),
      {"row",
         {"margin=10",       style = {margin = 10,       bg = colors.blue}},
         {"margin_left=20",  style = {margin_left = 20,  bg = colors.blue}},
         {"margin_right=20", style = {margin_right = 20, bg = colors.blue}},
      },
      {"row",
         {"margin_top=20",    style = {margin_top    = 20, bg = colors.green}},
         {"margin_bottom=20", style = {margin_bottom = 20, bg = colors.green}},
         {"margin=0",         style = {margin = 0,         bg = colors.green}},
      },
   },

   FlushCells = {"col",
      {"[11/30] Flush Cells",                                       size = 40, style = s_title},
      {"margin_left=0 / margin_right=0 makes\nadjacent cells touch (no gap).", size = 50, style = s_desc},
      nav("Margin", "Borders"),
      {"row",
         {"Label:", style = {margin_right = 0, bg = {60, 60, 60}}},
         {"Value",  style = {margin_left = 0,  bg = {40, 40, 80}, pad_left = 6}},
      },
      {"row",
         {"Normal gap"},
         {"Normal gap"},
      },
      {"row",
         {"Flush A", style = {margin_right = 0, bg = {40, 80, 40}}},
         {"Flush B", style = {margin_left = 0, margin_right = 0, bg = {80, 40, 40}}},
         {"Flush C", style = {margin_left = 0, bg = {40, 40, 80}}},
      },
   },

   Borders = {"col",
      leaf_style = {border = {width = 0}},  -- reset so the demos below are unambiguous
      {"[12/30] Borders",                                           size = 40, style = s_title},
      {"border= draws a border.\nside= restricts to one edge.", size = 50, style = s_desc},
      nav("FlushCells", "ContainerBorder"),
      {"row", "no border", "no border", "no border"},
      {"row",
         {"width=4\ncolor=green",  style = {border = {width = 4, color = colors.green}}},
         {"width=4\nside=\"top\"",   style = {border = {width = 4, side = "top"}}},
         {"width=4\nside=\"right\"", style = {border = {width = 4, side = "right"}}},
         {"width=0",               style = {border = {width = 0}}},
      },
      {"row", "no border", "no border", "no border"},
      {"width=3, color=yellow", style = {border = {width = 3, color = colors.yellow}}},
   },

   ContainerBorder = {"col",
      {"[13/30] Container Border",                                  size = 40, style = s_title},
      {"border= on a container is only drawn\nwhen explicitly set (not inherited).", size = 50, style = s_desc},
      nav("Borders", "Clickable"),
      {"row", leaf_style = {border = {width = 0}},
         {"col", border = {width = 3, color = colors.green},
            {"Border on col"},
            {"(green, 3px)"},
         },
         {"col",
            {"No border"},
            {"on this col"},
         },
         {"col", border = {width = 2, color = colors.yellow},
            {"Border on col"},
            {"(yellow, 2px)"},
         },
      },
   },

   Clickable = {"col",
      {"[14/30] Press Callbacks",                                   size = 40, style = s_title},
      {"press={fn, args...} triggers\na Callbacks method on press.", size = 50, style = s_desc},
      nav("ContainerBorder", "Focusable"),
      {'press={"click"}',          press = {"click"}},
      {'press={"action","hello"}', press = {"action", "hello"}},
      {'press={"action","a","b"}', press = {"action", "a", "b"}},
   },

   Focusable = {"col",
      {"[15/30] Focus Behavior",                                    size = 40, style = s_title},
      {"Focused cell redraws with style.focused.\nDefault: focusable iff press= is set.", size = 50, style = s_desc},
      nav("Clickable", "FocusDisable"),
      {"row",
         {"press=\nfocusable=true",  press = {"click"}, focusable = true },
         {"press=\nfocusable=false", press = {"click"}, focusable = false},
      },
      {"row",
         {"label\nfocusable=true",  focusable = true },
         {"label\nfocusable=false", focusable = false},
      },
      {"row",
         {"press=\n(default)",  press = {"click"}},
         {"label\n(default)"},
      },
   },

   FocusDisable = {"col",
      {"[16/30] Focus Disable",                                     size = 40, style = s_title},
      {"focusable=false on a press= cell:\nbutton works but does not highlight.", size = 50, style = s_desc},
      nav("Focusable", "Dynamic"),
      {"row",
         {"col",
            {"With focus", size = 40, style = {font = fonts.myriad_small, border = {width = 0}}},
            {SYMBOL_OK .. " Confirm", press = {"click"}, focusable = true,
             style = s_btn},
         },
         {"col",
            {"Without focus", size = 40, style = {font = fonts.myriad_small, border = {width = 0}}},
            {SYMBOL_CLOSE .. " Cancel", press = {"click"}, focusable = false,
             style = s_btn},
         },
      },
   },

   Dynamic = {"col",
      {"[17/30] Dynamic Labels",                                    size = 40, style = s_title},
      {"lbl= cells get values via update_params().\nThey start blank; populate on first update.", size = 50, style = s_desc},
      nav("FocusDisable", "DynUpdate"),
      {lbl = "parameter One"},
      {lbl = "parameter Two"},
   },

   DynUpdate = {"col",
      {"[18/30] Dynamic Update API",                                size = 40, style = s_title},
      {"API is update_params() (not update_changes).\nPass &[(&str, &str)] to update lbl= cells.", size = 50, style = s_desc},
      nav("Dynamic", "Progress"),
      {"row",
         {"Param 1:", style = {margin_right = 0, bg = {60, 60, 60}}},
         {lbl = "parameter One", style = {margin_left = 0, pad_left = 6}},
      },
      {"row",
         {"Param 2:", style = {margin_right = 0, bg = {60, 60, 60}}},
         {lbl = "parameter Two", style = {margin_left = 0, pad_left = 6}},
      },
   },

   Progress = {"col",
      {"[19/30] Progress Bar",                                      size = 40, style = s_title},
      {'render="progress bar":\nlbl= value is a float in [0,1].', size = 50, style = s_desc},
      nav("DynUpdate", "Complex"),
      {lbl = "parameter One", render = "progress bar", style={pad=0}},
      {lbl = "parameter Two", render = "progress bar",
       style = {fg = colors.green, bg = {40, 40, 40}}},
      {"row",
         {lbl = "parameter One", render = "progress bar",
          style = {fg = colors.blue, bg = {40, 40, 40}}},
         {lbl = "parameter One"},
      },
   },

   Complex = {"col",
      {"[20/30] Nested Containers",                                 size = 40, style = s_title},
      {"Containers nest freely:\ncol in row, row in col...", size = 50, style = s_desc},
      nav("Progress", "Alignment"),
      {"row",
         {"col", "Top-left", "Bottom-left"},
         {"col",
            {"row", "TR-A", "TR-B"},
            {"row", "BR-A", "BR-B", "BR-C"},
         },
      },
   },

   Alignment = {"col",
      {"[21/30] Text Alignment",                                    size = 40, style = s_title},
      {"align= positions text within its cell.\nleft (default), center, right.", size = 50, style = s_desc},
      nav("Complex", "AlignStyle"),
         {"Left (default)"},
         {"Centered", align = "center"},
         {"Right aligned", align = "right"},
   },

   AlignStyle = {"col",
      {"[22/30] Align in Style Tables",                             size = 40, style = s_title},
      {"align works as flat prop, inside style=,\nand via leaf_style= on containers.", size = 50, style = s_desc},
      nav("Alignment", "MultilineAlign"),
      {"align=\"center\" (flat)", align = "center"},
      {"style={align=\"center\"}", style = {align = "center"}},
      {"row", leaf_style = {align = "right"},
         {"leaf right A"},
         {"leaf right B"},
      },
   },

   MultilineAlign = {"col",
      {"[23/30] Multiline Alignment",                               size = 40, style = s_title},
      {"Multiline text respects align=.\nEach line is aligned independently.", size = 50, style = s_desc},
      nav("AlignStyle", "DynAlign"),
      {"row",
         {"Line one\nLine two",   align = "left"},
         {"Center 1\nCenter 2",   align = "center"},
         {"Right A\nRight B",     align = "right"},
      },
   },

   DynAlign = {"col",
      {"[24/30] Dynamic Label Alignment",                           size = 40, style = s_title},
      {"lbl= cells also support align=.\nUses text_width() at runtime.", size = 50, style = s_desc},
      nav("MultilineAlign", "FontIcons"),
      {lbl = "parameter One", align = "left"},
      {lbl = "parameter Two", align = "center"},
      {lbl = "parameter Three", align = "right"},
   },

   FontIcons = {"col",
      {"[25/30] Font Chain + Icons + Extra",                        size = 40, style = s_title},
      {"Font chain: primary + FA fallback +\nextra code points (" .. PLUS_MINUS .. " " .. MICRO .. " " .. DEGREE .. ").", size = 50, style = s_desc},
      nav("DynAlign", "FocusGroups"),
      {"row", leaf_style = {font = fonts.myriad_icons_extra},
         {SYMBOL_HOME .. " Home"},
         {SYMBOL_SETTINGS .. " Settings"},
         {SYMBOL_SAVE .. " Save"},
      },
      {"row", leaf_style = {font = fonts.myriad_icons_extra},
         {SYMBOL_OK .. " " .. PLUS_MINUS .. "5V"},
         {SYMBOL_CLOSE .. " 25" .. DEGREE .. "C"},
         {SYMBOL_TRASH .. " 100" .. MICRO .. "A"},
      },
      {"row", leaf_style = {font = fonts.myriad_icons_extra},
         {SYMBOL_POWER .. " Power"},
         {SYMBOL_BACKSPACE .. " Back"},
         {"No icons here"},
      },
   },

   Popup = {"col",
      menu_size  = {math.floor(0.5 * screen.width), math.floor(0.7 * screen.height)},
      menu_align = {math.floor(0.5 * screen.width), math.floor(0.5 * screen.height)},
      menu_anchor = "center",
      border = {width = 2, color = colors.white},
      {"[32/32] Popup Positioning",                                 size = 40, style = s_title},
      {"menu_size={w,h}: menu size in pixels.\nmenu_align={x,y}+menu_anchor=: position.", size = 50, style = s_desc},
      nav("Widgets", "Hello"),
   },
}

-- Insert FocusGroups and Overload before Popup in navigation
menus.FocusGroups = {"col",
   {"[26/30] Focus Groups",                                       size = 40, style = s_title},
   {"focus_index= groups elements into\na single focusable unit.", size = 50, style = s_desc},
   nav("FontIcons", "Overload"),
   {"row",
      {"Label", focus_index = 50,
       focused = {border = {width = 3, color = colors.green, side = {"top", "bottom", "left"}}},
       style = {margin = 0, margin_left = 4}},
      {lbl = "parameter One", render = "progress bar", focus_index = 50,
       focused = {border = {width = 3, color = colors.green, side = {"top", "bottom", "right"}}},
       style = {pad = 10, margin = 0, margin_right = 4, fg = colors.green}},
   },
   {"Click either Label or the bar.\nBoth highlight as one unit.", style = {border = {width = 0}}},
}

menus.Overload = {"col",
   {"[27/30] Progress Bar Overload",                               size = 40, style = s_title},
   {"overload={r,g,b}: bar turns this\ncolor when value reaches 1.0.", size = 50, style = s_desc},
   nav("FocusGroups", "Icons"),
   {"row",
      {"Normal bar:", weight = 2},
      {lbl = "parameter One", render = "progress bar",
       style = {pad = 10, fg = colors.green}},
   },
   {"row",
      {"Overload bar:", weight = 2},
      {lbl = "parameter Two", render = "progress bar",
       overload = colors.red,
       style = {pad = 10, fg = colors.green}},
   },
   {"The bottom bar turns red when\nits value reaches or exceeds 1.0.", style = {border = {width = 0}}},
}

menus.Icons = {"col",
   {"[28/30] SVG Icons",                                          size = 40, style = s_title},
   {"icon= renders a pre-rasterized SVG.\nAlpha-blended at draw time (fg/bg).", size = 50, style = s_desc},
   nav("Overload", "ActiveStyle"),
   {"row", leaf_style = {border = {width = 0}},
      {"col",
         {"small", size = 25, style = {font = fonts.myriad_small, border = {width = 0}}},
         {icon = "icons/lpf.svg", style = {pad = 55, border = {width = 0}}},
      },
      {"col",
         {"medium", size = 25, style = {font = fonts.myriad_small, border = {width = 0}}},
         {icon = "icons/lpf.svg", style = {pad = 35, border = {width = 0}}},
      },
      {"col",
         {"large", size = 25, style = {font = fonts.myriad_small, border = {width = 0}}},
         {icon = "icons/lpf.svg", style = {pad = 10, border = {width = 0}}},
      },
      {"col",
         {"full", size = 25, style = {font = fonts.myriad_small, border = {width = 0}}},
         {icon = "icons/lpf.svg", style = {pad = 0, border = {width = 0}}},
      },
   },
   {"row", leaf_style = {border = {width = 0}},
      {"col",
         {"white on blue", size = 25, style = {font = fonts.myriad_small, border = {width = 0}}},
         {icon = "icons/lpf.svg", style = {bg = {16, 28, 55}}},
      },
      {"col",
         {"white on gray", size = 25, style = {font = fonts.myriad_small, border = {width = 0}}},
         {icon = "icons/lpf.svg", style = {bg = {60, 60, 60}}},
      },
      {"col",
         {"green on black", size = 25, style = {font = fonts.myriad_small, border = {width = 0}}},
         {icon = "icons/lpf.svg", style = {fg = colors.green}},
      },
      {"col",
         {"red on white", size = 25, style = {font = fonts.myriad_small, border = {width = 0}}},
         {icon = "icons/lpf.svg", style = {fg = colors.red, bg = colors.white}},
      },
   },
}

menus.ActiveStyle = {"col",
   {"[29/31] Active Styling",                                     size = 40, style = s_title},
   {"active={border=...}: app-controlled\nstyle via set_active(text, bool).", size = 50, style = s_desc},
   nav("Icons", "MidString"),
   {"row",
      {"Option A", weight = 1, press = {"action", "a"},
       active = {bg = {30, 80, 30}, border = {width = 2, color = colors.green}},
       style = {bg = {30, 30, 80}, margin = 6, align = "center",
                border = {width = 1, color = {100,100,100}}}},
      {"Option B", weight = 1, press = {"action", "b"},
       active = {bg = {30, 80, 30}, border = {width = 2, color = colors.green}},
       style = {bg = {30, 30, 80}, margin = 6, align = "center",
                border = {width = 1, color = {100,100,100}}}},
      {"Option C", weight = 1, press = {"action", "c"},
       active = {bg = {30, 80, 30}, border = {width = 2, color = colors.green}},
       style = {bg = {30, 30, 80}, margin = 6, align = "center",
                border = {width = 1, color = {100,100,100}}}},
   },
   {"Click a button to see the underline.\nApp calls set_active() to toggle.", style = {border = {width = 0}}},
}

menus.MidString = {"col",
   {"[30/32] Mid-String Font/Color Change",                       size = 40, style = s_title},
   {"blit() returns ending x, so chained\ncalls can change font/color mid-text.", size = 50, style = s_desc},
   nav("ActiveStyle", "Widgets"),
   -- Row with segments in different fonts (rendered by app code, not transpiler)
   {"row", size = 50,
      {"Large+", weight = 1, style = {font = fonts.myriad_large, fg = colors.white}},
      {"small", weight = 1, style = {font = fonts.myriad_small, fg = colors.yellow}},
   },
   {"row", size = 50,
      {"Mono:", weight = 1, style = {font = fonts.roboto_large, fg = colors.green}},
      {"Proportional", weight = 1, style = {font = fonts.myriad_large, fg = colors.white}},
   },
   {"The transpiler places each segment\nas its own cell. blit() chaining is\nfor app-level code (see Backend::blit).", style = {border = {width = 0}}},
}

-- Ribbon color function: hue sweep from blue to red
local function hue_ribbon(t)
   -- HSV with H from 240° (blue) to 0° (red) as t goes 0→1
   local h = (1 - t) * 240
   local s, v = 1.0, 1.0
   local c = v * s
   local x = c * (1 - math.abs((h / 60) % 2 - 1))
   local m = v - c
   local r, g, b
   if h < 60 then r, g, b = c, x, 0
   elseif h < 120 then r, g, b = x, c, 0
   elseif h < 180 then r, g, b = 0, c, x
   elseif h < 240 then r, g, b = 0, x, c
   else r, g, b = x, 0, c end
   return {math.floor((r + m) * 255), math.floor((g + m) * 255), math.floor((b + m) * 255)}
end

menus.Widgets = {"col",
   {"[31/32] Widgets: Progress Bar + Slider",                    size = 40, style = s_title},
   {"render=\"progress bar\" and\nrender=\"pointer slider\" (with ribbon=).", size = 50, style = s_desc},
   nav("MidString", "Popup"),
   {"row",
      {"Progress:", weight = 1},
      {lbl = "parameter One", render = "progress bar",
       style = {pad = 10, fg = colors.green}},
   },
   {"row",
      {"Slider:", weight = 1},
      {lbl = "parameter One", render = "pointer slider", size = 20,
       ribbon = hue_ribbon,
       style = {pad = 2, fg = colors.white}},
   },
   {"The slider shows a white triangle\nover a hue-sweep ribbon. Both track\nthe same parameter.", style = {border = {width = 0}}},
}
