use crate::{PixelFormat, Renderer};
use std::collections::HashMap;

/// Atlas created from pre-baked alpha data (generated by gen_font_atlas.py).
/// Stores a 256-entry color lookup table (indexed by alpha value) and a
/// reference to the raw alpha bitmap. Blitting resolves colors on the fly
/// via the LUT, avoiding a large pre-blended pixel buffer.
pub struct PrebakedAtlas<P: PixelFormat> {
    cell_h: usize,
    ascii_adv: [usize; 128],
    ascii_off: [usize; 128],
    ext: HashMap<u32, (usize, usize)>,
    alpha: &'static [u8],
    lut: [P; 256],
}

impl<P: PixelFormat> PrebakedAtlas<P> {
    pub fn from_alpha(
        cell_h: usize,
        ascii_adv: &[usize; 128],
        ascii_off: &[usize; 128],
        ext: &[(u32, usize, usize)],
        alpha: &'static [u8],
        fg: P,
        bg: P,
    ) -> Self {
        let (fr, fg_, fb) = fg.to_rgb();
        let (br, bg_, bb) = bg.to_rgb();
        let (fr, fg_, fb) = (fr as u32, fg_ as u32, fb as u32);
        let (br, bg_, bb) = (br as u32, bg_ as u32, bb as u32);
        let mut lut = [P::default(); 256];
        for a in 0u32..256 {
            let inv = 255 - a;
            lut[a as usize] = P::from_rgb(
                ((fr * a + br * inv) / 255) as u8,
                ((fg_ * a + bg_ * inv) / 255) as u8,
                ((fb * a + bb * inv) / 255) as u8,
            );
        }
        let ext_map = ext.iter().map(|&(cp, off, adv)| (cp, (off, adv))).collect();
        PrebakedAtlas {
            cell_h,
            ascii_adv: *ascii_adv,
            ascii_off: *ascii_off,
            ext: ext_map,
            alpha,
            lut,
        }
    }

    #[inline]
    fn glyph_alpha(&self, c: char) -> Option<(&[u8], usize)> {
        let cp = c as u32;
        let (off, gw) = if cp < 128 {
            let gw = self.ascii_adv[cp as usize];
            if gw == 0 { return None; }
            (self.ascii_off[cp as usize], gw)
        } else {
            let &(off, gw) = self.ext.get(&cp)?;
            (off, gw)
        };
        let end = off + gw * self.cell_h;
        if end <= self.alpha.len() {
            Some((&self.alpha[off..end], gw))
        } else {
            None
        }
    }

    fn try_ligature(chars: &[char], i: usize, atlas: &Self) -> (char, usize) {
        if chars[i] == 'f' {
            if i + 2 < chars.len() && chars[i+1] == 'f' && chars[i+2] == 'i'
                && atlas.glyph_alpha('\u{FB03}').is_some() { return ('\u{FB03}', 3); }
            if i + 2 < chars.len() && chars[i+1] == 'f' && chars[i+2] == 'l'
                && atlas.glyph_alpha('\u{FB04}').is_some() { return ('\u{FB04}', 3); }
            if i + 1 < chars.len() && chars[i+1] == 'i'
                && atlas.glyph_alpha('\u{FB01}').is_some() { return ('\u{FB01}', 2); }
            if i + 1 < chars.len() && chars[i+1] == 'l'
                && atlas.glyph_alpha('\u{FB02}').is_some() { return ('\u{FB02}', 2); }
            if i + 1 < chars.len() && chars[i+1] == 'f'
                && atlas.glyph_alpha('\u{FB00}').is_some() { return ('\u{FB00}', 2); }
        }
        (chars[i], 1)
    }
}

impl<P: PixelFormat> Renderer<P> for PrebakedAtlas<P> {
    fn blit(&self, fb: &mut [P], stride: usize, x: usize, y: usize, text: &str) -> usize {
        let ch = self.cell_h;
        let fb_len = fb.len();
        let lut = &self.lut;
        let mut cx = x;
        let chars: Vec<char> = text.chars().collect();
        let mut i = 0;
        while i < chars.len() {
            let (c, skip) = Self::try_ligature(&chars, i, self);
            if skip > 1 { cx = cx.saturating_sub(3); }
            i += skip;
            if let Some((src_alpha, gw)) = self.glyph_alpha(c) {
                for gy in 0..ch {
                    let dst = (y + gy) * stride + cx;
                    if dst + gw <= fb_len {
                        let row = &src_alpha[gy * gw..(gy + 1) * gw];
                        let out = &mut fb[dst..dst + gw];
                        for (o, &a) in out.iter_mut().zip(row) {
                            *o = lut[a as usize];
                        }
                    }
                }
                cx += gw;
            }
        }
        cx
    }

    fn cell_height(&self) -> usize { self.cell_h }

    fn char_width(&self, c: char) -> usize {
        let cp = c as u32;
        if cp < 128 {
            self.ascii_adv[cp as usize]
        } else {
            self.ext.get(&cp).map(|&(_, gw)| gw).unwrap_or(0)
        }
    }

    fn text_width(&self, text: &str) -> usize {
        let chars: Vec<char> = text.chars().collect();
        let mut w = 0;
        let mut i = 0;
        while i < chars.len() {
            let (c, skip) = Self::try_ligature(&chars, i, self);
            w += self.char_width(c);
            if skip > 1 { w = w.saturating_sub(3); }
            i += skip;
        }
        w
    }
}
