use crate::{Pixel, Renderer};
use std::collections::HashMap;

/// Atlas created from pre-baked alpha data (generated by gen_font_atlas.py).
/// Color blending happens at init time — no TTF files needed at runtime.
pub struct PrebakedAtlas {
    cell_h: usize,
    ascii_adv: [usize; 128],
    ascii_off: [usize; 128],
    ext: HashMap<u32, (usize, usize)>,
    buf: Vec<Pixel>,
}

impl PrebakedAtlas {
    pub fn from_alpha(
        cell_h: usize,
        ascii_adv: &[usize; 128],
        ascii_off: &[usize; 128],
        ext: &[(u32, usize, usize)],
        alpha: &[u8],
        fg: Pixel,
        bg: Pixel,
    ) -> Self {
        let fg_rgb = to_rgb888(fg);
        let bg_rgb = to_rgb888(bg);
        let buf: Vec<Pixel> = alpha.iter().map(|&a| {
            let a = a as u32;
            let inv = 255 - a;
            let r = (fg_rgb.0 * a + bg_rgb.0 * inv) / 255;
            let g = (fg_rgb.1 * a + bg_rgb.1 * inv) / 255;
            let b = (fg_rgb.2 * a + bg_rgb.2 * inv) / 255;
            rgb888_to_pixel(r, g, b)
        }).collect();
        let ext_map = ext.iter().map(|&(cp, off, adv)| (cp, (off, adv))).collect();
        PrebakedAtlas {
            cell_h,
            ascii_adv: *ascii_adv,
            ascii_off: *ascii_off,
            ext: ext_map,
            buf,
        }
    }

    #[inline]
    fn glyph_by_char(&self, c: char) -> Option<(&[Pixel], usize)> {
        let cp = c as u32;
        let (off, gw) = if cp < 128 {
            let gw = self.ascii_adv[cp as usize];
            if gw == 0 { return None; }
            (self.ascii_off[cp as usize], gw)
        } else {
            let &(off, gw) = self.ext.get(&cp)?;
            (off, gw)
        };
        let end = off + gw * self.cell_h;
        if end <= self.buf.len() {
            Some((&self.buf[off..end], gw))
        } else {
            None
        }
    }

    fn try_ligature(chars: &[char], i: usize, atlas: &Self) -> (char, usize) {
        if chars[i] == 'f' {
            if i + 2 < chars.len() && chars[i+1] == 'f' && chars[i+2] == 'i'
                && atlas.glyph_by_char('\u{FB03}').is_some() { return ('\u{FB03}', 3); }
            if i + 2 < chars.len() && chars[i+1] == 'f' && chars[i+2] == 'l'
                && atlas.glyph_by_char('\u{FB04}').is_some() { return ('\u{FB04}', 3); }
            if i + 1 < chars.len() && chars[i+1] == 'i'
                && atlas.glyph_by_char('\u{FB01}').is_some() { return ('\u{FB01}', 2); }
            if i + 1 < chars.len() && chars[i+1] == 'l'
                && atlas.glyph_by_char('\u{FB02}').is_some() { return ('\u{FB02}', 2); }
            if i + 1 < chars.len() && chars[i+1] == 'f'
                && atlas.glyph_by_char('\u{FB00}').is_some() { return ('\u{FB00}', 2); }
        }
        (chars[i], 1)
    }
}

impl Renderer for PrebakedAtlas {
    fn blit(&self, fb: &mut [Pixel], stride: usize, x: usize, y: usize, text: &str) -> usize {
        let ch = self.cell_h;
        let fb_len = fb.len();
        let mut cx = x;
        let chars: Vec<char> = text.chars().collect();
        let mut i = 0;
        while i < chars.len() {
            let (c, skip) = Self::try_ligature(&chars, i, self);
            if skip > 1 { cx = cx.saturating_sub(3); }
            i += skip;
            if let Some((src, gw)) = self.glyph_by_char(c) {
                for gy in 0..ch {
                    let dst = (y + gy) * stride + cx;
                    if dst + gw <= fb_len {
                        fb[dst..dst + gw].copy_from_slice(&src[gy * gw..(gy + 1) * gw]);
                    }
                }
                cx += gw;
            }
        }
        cx
    }

    fn cell_height(&self) -> usize { self.cell_h }

    fn char_width(&self, c: char) -> usize {
        let cp = c as u32;
        if cp < 128 {
            self.ascii_adv[cp as usize]
        } else {
            self.ext.get(&cp).map(|&(_, gw)| gw).unwrap_or(0)
        }
    }

    fn text_width(&self, text: &str) -> usize {
        let chars: Vec<char> = text.chars().collect();
        let mut w = 0;
        let mut i = 0;
        while i < chars.len() {
            let (c, skip) = Self::try_ligature(&chars, i, self);
            w += self.char_width(c);
            if skip > 1 { w = w.saturating_sub(3); }
            i += skip;
        }
        w
    }
}

// --- Pixel format helpers (same as ttf.rs) ---

#[cfg(feature = "bpp16")]
fn to_rgb888(p: Pixel) -> (u32, u32, u32) {
    (((p as u32 >> 11) & 0x1F) << 3, ((p as u32 >> 5) & 0x3F) << 2, ((p as u32) & 0x1F) << 3)
}
#[cfg(feature = "bpp32")]
fn to_rgb888(p: Pixel) -> (u32, u32, u32) {
    ((p as u32 >> 16) & 0xFF, (p as u32 >> 8) & 0xFF, (p as u32) & 0xFF)
}
#[cfg(feature = "bpp32rgba")]
fn to_rgb888(p: Pixel) -> (u32, u32, u32) {
    (p & 0xFF, (p >> 8) & 0xFF, (p >> 16) & 0xFF)
}
#[cfg(feature = "bpp16")]
fn rgb888_to_pixel(r: u32, g: u32, b: u32) -> Pixel {
    (((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)) as Pixel
}
#[cfg(feature = "bpp32")]
fn rgb888_to_pixel(r: u32, g: u32, b: u32) -> Pixel {
    ((r << 16) | (g << 8) | b) as Pixel
}
#[cfg(feature = "bpp32rgba")]
fn rgb888_to_pixel(r: u32, g: u32, b: u32) -> Pixel {
    r | (g << 8) | (b << 16) | 0xFF000000
}
