// Generated by scripts/layout.lua — do not edit.
// Re-run the transpiler to update:
//   lua scripts/layout.lua < examples/ui.lua > examples/app/ui.rs
// transpiler: b65e7c4ea1f4b5786644842608b8b5b157ef96d8e51f138519b5c518d53a263b
// input:      746dce563ccfeeb561102f88e6a9f94e89728afd35151732be8d293874e94d60

use imgrids::{rgb, Backend, InputEvent, Renderer};
use imgrids::ttf::TtfAtlas;
use std::sync::OnceLock;
use std::sync::Mutex;

static ATLAS_1: OnceLock<TtfAtlas> = OnceLock::new();
fn atlas_1() -> &'static TtfAtlas {
    ATLAS_1.get_or_init(|| TtfAtlas::new("fonts/RobotoMono-Regular.ttf", 20, rgb!(255, 255, 255), rgb!(60, 60, 60))
        .expect("fonts/RobotoMono-Regular.ttf"))
}

static ATLAS_2: OnceLock<TtfAtlas> = OnceLock::new();
fn atlas_2() -> &'static TtfAtlas {
    ATLAS_2.get_or_init(|| TtfAtlas::new("fonts/RobotoMono-Regular.ttf", 20, rgb!(255, 255, 255), rgb!(0, 0, 0))
        .expect("fonts/RobotoMono-Regular.ttf"))
}

static ATLAS_3: OnceLock<TtfAtlas> = OnceLock::new();
fn atlas_3() -> &'static TtfAtlas {
    ATLAS_3.get_or_init(|| TtfAtlas::new("fonts/RobotoMono-Regular.ttf", 32, rgb!(255, 255, 255), rgb!(0, 0, 0))
        .expect("fonts/RobotoMono-Regular.ttf"))
}

static ATLAS_4: OnceLock<TtfAtlas> = OnceLock::new();
fn atlas_4() -> &'static TtfAtlas {
    ATLAS_4.get_or_init(|| TtfAtlas::new("fonts/RobotoMono-Regular.ttf", 32, rgb!(255, 255, 255), rgb!(30, 80, 180))
        .expect("fonts/RobotoMono-Regular.ttf"))
}

static ATLAS_5: OnceLock<TtfAtlas> = OnceLock::new();
fn atlas_5() -> &'static TtfAtlas {
    ATLAS_5.get_or_init(|| TtfAtlas::new("fonts/RobotoMono-Regular.ttf", 32, rgb!(255, 255, 255), rgb!(0, 0, 255))
        .expect("fonts/RobotoMono-Regular.ttf"))
}

static ATLAS_6: OnceLock<TtfAtlas> = OnceLock::new();
fn atlas_6() -> &'static TtfAtlas {
    ATLAS_6.get_or_init(|| TtfAtlas::new("fonts/RobotoMono-Regular.ttf", 32, rgb!(255, 255, 255), rgb!(255, 0, 0))
        .expect("fonts/RobotoMono-Regular.ttf"))
}

static ATLAS_7: OnceLock<TtfAtlas> = OnceLock::new();
fn atlas_7() -> &'static TtfAtlas {
    ATLAS_7.get_or_init(|| TtfAtlas::new("fonts/RobotoMono-Regular.ttf", 32, rgb!(0, 0, 0), rgb!(0, 255, 0))
        .expect("fonts/RobotoMono-Regular.ttf"))
}

static ATLAS_8: OnceLock<TtfAtlas> = OnceLock::new();
fn atlas_8() -> &'static TtfAtlas {
    ATLAS_8.get_or_init(|| TtfAtlas::new("fonts/RobotoMono-Regular.ttf", 32, rgb!(255, 255, 255), rgb!(60, 60, 120))
        .expect("fonts/RobotoMono-Regular.ttf"))
}

static ATLAS_9: OnceLock<TtfAtlas> = OnceLock::new();
fn atlas_9() -> &'static TtfAtlas {
    ATLAS_9.get_or_init(|| TtfAtlas::new("fonts/RobotoMono-Regular.ttf", 32, rgb!(255, 255, 255), rgb!(60, 120, 60))
        .expect("fonts/RobotoMono-Regular.ttf"))
}

static ATLAS_10: OnceLock<TtfAtlas> = OnceLock::new();
fn atlas_10() -> &'static TtfAtlas {
    ATLAS_10.get_or_init(|| TtfAtlas::new("fonts/RobotoMono-Regular.ttf", 32, rgb!(255, 255, 255), rgb!(120, 60, 60))
        .expect("fonts/RobotoMono-Regular.ttf"))
}

static ATLAS_11: OnceLock<TtfAtlas> = OnceLock::new();
fn atlas_11() -> &'static TtfAtlas {
    ATLAS_11.get_or_init(|| TtfAtlas::new("fonts/RobotoMono-Regular.ttf", 32, rgb!(255, 255, 255), rgb!(0, 255, 0))
        .expect("fonts/RobotoMono-Regular.ttf"))
}

#[derive(Clone, Copy, PartialEq)]
pub enum Menu {
    Borders,
    CellStyle,
    Clickable,
    Cols,
    Complex,
    Dynamic,
    Fixed,
    Focusable,
    Hello,
    Margin,
    Pad,
    Popup,
    Progress,
    Rows,
    Weighted,
}

static CURRENT_MENU: Mutex<Option<Menu>> = Mutex::new(None);
static FOCUSED: Mutex<Option<usize>> = Mutex::new(None);
static LAST_DRAWN_FOCUS: Mutex<Option<usize>> = Mutex::new(Some(usize::MAX));

use std::sync::atomic::{AtomicUsize, Ordering};
static PROG_1_PREV: AtomicUsize = AtomicUsize::new(usize::MAX);
static PROG_2_PREV: AtomicUsize = AtomicUsize::new(usize::MAX);
static PROG_3_PREV: AtomicUsize = AtomicUsize::new(usize::MAX);

pub trait Callbacks {
    fn quit(&mut self);
    fn action(&mut self, args: &[&str]);
    fn click(&mut self);
    fn nav(&mut self, args: &[&str]);
}

pub fn to_menu(name: &str) -> Option<Menu> {
    match name {
        "Borders" => Some(Menu::Borders),
        "CellStyle" => Some(Menu::CellStyle),
        "Clickable" => Some(Menu::Clickable),
        "Cols" => Some(Menu::Cols),
        "Complex" => Some(Menu::Complex),
        "Dynamic" => Some(Menu::Dynamic),
        "Fixed" => Some(Menu::Fixed),
        "Focusable" => Some(Menu::Focusable),
        "Hello" => Some(Menu::Hello),
        "Margin" => Some(Menu::Margin),
        "Pad" => Some(Menu::Pad),
        "Popup" => Some(Menu::Popup),
        "Progress" => Some(Menu::Progress),
        "Rows" => Some(Menu::Rows),
        "Weighted" => Some(Menu::Weighted),
        _ => None,
    }
}

pub fn update_events<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Quit = ev { state.quit(); return; }
    }
    match *CURRENT_MENU.lock().unwrap() {
        Some(Menu::Borders) => update_events_borders(events, state),
        Some(Menu::CellStyle) => update_events_cellstyle(events, state),
        Some(Menu::Clickable) => update_events_clickable(events, state),
        Some(Menu::Cols) => update_events_cols(events, state),
        Some(Menu::Complex) => update_events_complex(events, state),
        Some(Menu::Dynamic) => update_events_dynamic(events, state),
        Some(Menu::Fixed) => update_events_fixed(events, state),
        Some(Menu::Focusable) => update_events_focusable(events, state),
        Some(Menu::Hello) => update_events_hello(events, state),
        Some(Menu::Margin) => update_events_margin(events, state),
        Some(Menu::Pad) => update_events_pad(events, state),
        Some(Menu::Popup) => update_events_popup(events, state),
        Some(Menu::Progress) => update_events_progress(events, state),
        Some(Menu::Rows) => update_events_rows(events, state),
        Some(Menu::Weighted) => update_events_weighted(events, state),
        None => {}
    }
}

pub fn update_menu(backend: &mut dyn Backend, menu: Menu) {
    let mut current = CURRENT_MENU.lock().unwrap();
    if *current != Some(menu) {
        *current = Some(menu);
        drop(current);
        *FOCUSED.lock().unwrap() = None;
        *LAST_DRAWN_FOCUS.lock().unwrap() = None;
        PROG_1_PREV.store(usize::MAX, Ordering::Relaxed);
        PROG_2_PREV.store(usize::MAX, Ordering::Relaxed);
        PROG_3_PREV.store(usize::MAX, Ordering::Relaxed);
        match menu {
            Menu::Borders => draw_borders(backend),
            Menu::CellStyle => draw_cellstyle(backend),
            Menu::Clickable => draw_clickable(backend),
            Menu::Cols => draw_cols(backend),
            Menu::Complex => draw_complex(backend),
            Menu::Dynamic => draw_dynamic(backend),
            Menu::Fixed => draw_fixed(backend),
            Menu::Focusable => draw_focusable(backend),
            Menu::Hello => draw_hello(backend),
            Menu::Margin => draw_margin(backend),
            Menu::Pad => draw_pad(backend),
            Menu::Popup => draw_popup(backend),
            Menu::Progress => draw_progress(backend),
            Menu::Rows => draw_rows(backend),
            Menu::Weighted => draw_weighted(backend),
        }
        backend.flush();
    }
}

pub fn update_changes(backend: &mut dyn Backend, changes: &[(&str, &str)]) {
    match *CURRENT_MENU.lock().unwrap() {
        Some(Menu::Borders) => update_changes_borders(backend, changes),
        Some(Menu::CellStyle) => update_changes_cellstyle(backend, changes),
        Some(Menu::Clickable) => update_changes_clickable(backend, changes),
        Some(Menu::Cols) => update_changes_cols(backend, changes),
        Some(Menu::Complex) => update_changes_complex(backend, changes),
        Some(Menu::Dynamic) => update_changes_dynamic(backend, changes),
        Some(Menu::Fixed) => update_changes_fixed(backend, changes),
        Some(Menu::Focusable) => update_changes_focusable(backend, changes),
        Some(Menu::Hello) => update_changes_hello(backend, changes),
        Some(Menu::Margin) => update_changes_margin(backend, changes),
        Some(Menu::Pad) => update_changes_pad(backend, changes),
        Some(Menu::Popup) => update_changes_popup(backend, changes),
        Some(Menu::Progress) => update_changes_progress(backend, changes),
        Some(Menu::Rows) => update_changes_rows(backend, changes),
        Some(Menu::Weighted) => update_changes_weighted(backend, changes),
        None => {}
    }
    backend.flush();
}

fn draw_borders(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    backend.fill_rect(0, 0, 800, 40, rgb!(60, 60, 60));
    atlas_1().draw(backend, 10, 10, "border=");
    backend.fill_rect(0, 40, 800, 50, rgb!(0, 0, 0));
    atlas_2().draw(backend, 10, 44, "border= draws a border.");
    atlas_2().draw(backend, 10, 66, "side= restricts to one edge.");
    backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 106, 104, "Prev");
    backend.draw_border(104, 94, 192, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 506, 104, "Next");
    backend.draw_border(504, 94, 192, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(0, 150, 266, 82, rgb!(0, 0, 0));
    atlas_3().draw(backend, 1, 175, "no border");
    backend.draw_border(0, 150, 266, 82, 1, rgb!(255, 255, 255));
    backend.fill_rect(266, 150, 266, 82, rgb!(0, 0, 0));
    atlas_3().draw(backend, 267, 175, "no border");
    backend.draw_border(266, 150, 266, 82, 1, rgb!(255, 255, 255));
    backend.fill_rect(532, 150, 268, 82, rgb!(0, 0, 0));
    atlas_3().draw(backend, 533, 175, "no border");
    backend.draw_border(532, 150, 268, 82, 1, rgb!(255, 255, 255));
    backend.fill_rect(0, 232, 200, 82, rgb!(0, 0, 0));
    atlas_3().draw(backend, 4, 240, "width=4");
    atlas_3().draw(backend, 4, 274, "color=green");
    backend.draw_border(0, 232, 200, 82, 4, rgb!(0, 255, 0));
    backend.fill_rect(200, 232, 200, 82, rgb!(0, 0, 0));
    atlas_3().draw(backend, 200, 242, "width=4");
    atlas_3().draw(backend, 200, 276, "side=\"top\"");
    backend.fill_rect(200, 232, 200, 4, rgb!(255, 255, 255));
    backend.fill_rect(400, 232, 200, 82, rgb!(0, 0, 0));
    atlas_3().draw(backend, 400, 240, "width=4");
    atlas_3().draw(backend, 400, 274, "side=\"right\"");
    backend.fill_rect(596, 232, 4, 82, rgb!(255, 255, 255));
    backend.fill_rect(600, 232, 200, 82, rgb!(0, 0, 0));
    atlas_3().draw(backend, 600, 257, "width=0");
    backend.fill_rect(0, 314, 266, 82, rgb!(0, 0, 0));
    atlas_3().draw(backend, 1, 339, "no border");
    backend.draw_border(0, 314, 266, 82, 1, rgb!(255, 255, 255));
    backend.fill_rect(266, 314, 266, 82, rgb!(0, 0, 0));
    atlas_3().draw(backend, 267, 339, "no border");
    backend.draw_border(266, 314, 266, 82, 1, rgb!(255, 255, 255));
    backend.fill_rect(532, 314, 268, 82, rgb!(0, 0, 0));
    atlas_3().draw(backend, 533, 339, "no border");
    backend.draw_border(532, 314, 268, 82, 1, rgb!(255, 255, 255));
    backend.fill_rect(0, 396, 800, 84, rgb!(0, 0, 0));
    atlas_3().draw(backend, 3, 422, "width=3, color=yellow");
    backend.draw_border(0, 396, 800, 84, 3, rgb!(255, 255, 0));
}

fn draw_cellstyle(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    backend.fill_rect(0, 0, 800, 40, rgb!(60, 60, 60));
    atlas_1().draw(backend, 10, 10, "style=");
    backend.fill_rect(0, 40, 800, 50, rgb!(0, 0, 0));
    atlas_2().draw(backend, 10, 44, "Each cell carries a style= table.");
    atlas_2().draw(backend, 10, 66, "Reuse named tables to share style.");
    backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 106, 104, "Prev");
    backend.draw_border(104, 94, 192, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 506, 104, "Next");
    backend.draw_border(504, 94, 192, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(0, 150, 200, 330, rgb!(0, 0, 255));
    atlas_5().draw(backend, 1, 299, "blue cell");
    backend.draw_border(0, 150, 200, 330, 1, rgb!(255, 255, 255));
    backend.fill_rect(200, 150, 200, 330, rgb!(0, 0, 0));
    atlas_3().draw(backend, 201, 299, "default");
    backend.draw_border(200, 150, 200, 330, 1, rgb!(255, 255, 255));
    backend.fill_rect(400, 150, 200, 330, rgb!(255, 0, 0));
    atlas_6().draw(backend, 401, 299, "red cell");
    backend.draw_border(400, 150, 200, 330, 1, rgb!(255, 255, 255));
    backend.fill_rect(600, 150, 200, 330, rgb!(0, 255, 0));
    atlas_7().draw(backend, 601, 299, "green cell");
    backend.draw_border(600, 150, 200, 330, 1, rgb!(255, 255, 255));
}

fn draw_clickable(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    backend.fill_rect(0, 0, 800, 40, rgb!(60, 60, 60));
    atlas_1().draw(backend, 10, 10, "press= callbacks");
    backend.fill_rect(0, 40, 800, 50, rgb!(0, 0, 0));
    atlas_2().draw(backend, 10, 44, "press={fn, args...} triggers");
    atlas_2().draw(backend, 10, 66, "a Callbacks method on press.");
    backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 106, 104, "Prev");
    backend.draw_border(104, 94, 192, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 506, 104, "Next");
    backend.draw_border(504, 94, 192, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(0, 150, 800, 110, rgb!(0, 0, 0));
    atlas_3().draw(backend, 1, 189, "press={\"click\"}");
    backend.draw_border(0, 150, 800, 110, 1, rgb!(255, 255, 255));
    backend.fill_rect(0, 260, 800, 110, rgb!(0, 0, 0));
    atlas_3().draw(backend, 1, 299, "press={\"action\",\"hello\"}");
    backend.draw_border(0, 260, 800, 110, 1, rgb!(255, 255, 255));
    backend.fill_rect(0, 370, 800, 110, rgb!(0, 0, 0));
    atlas_3().draw(backend, 1, 409, "press={\"action\",\"a\",\"b\"}");
    backend.draw_border(0, 370, 800, 110, 1, rgb!(255, 255, 255));
}

fn draw_cols(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    backend.fill_rect(0, 0, 800, 40, rgb!(60, 60, 60));
    atlas_1().draw(backend, 10, 10, "col + row nesting");
    backend.fill_rect(0, 40, 800, 50, rgb!(0, 0, 0));
    atlas_2().draw(backend, 10, 44, "col inside a row:");
    atlas_2().draw(backend, 10, 66, "each column stacks its own children.");
    backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 106, 104, "Prev");
    backend.draw_border(104, 94, 192, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 506, 104, "Next");
    backend.draw_border(504, 94, 192, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(0, 150, 266, 110, rgb!(0, 0, 0));
    atlas_3().draw(backend, 1, 189, "Col A top");
    backend.draw_border(0, 150, 266, 110, 1, rgb!(255, 255, 255));
    backend.fill_rect(0, 260, 266, 110, rgb!(0, 0, 0));
    atlas_3().draw(backend, 1, 299, "Col A mid");
    backend.draw_border(0, 260, 266, 110, 1, rgb!(255, 255, 255));
    backend.fill_rect(0, 370, 266, 110, rgb!(0, 0, 0));
    atlas_3().draw(backend, 1, 409, "Col A bot");
    backend.draw_border(0, 370, 266, 110, 1, rgb!(255, 255, 255));
    backend.fill_rect(266, 150, 266, 110, rgb!(0, 0, 0));
    atlas_3().draw(backend, 267, 189, "Col B top");
    backend.draw_border(266, 150, 266, 110, 1, rgb!(255, 255, 255));
    backend.fill_rect(266, 260, 266, 110, rgb!(0, 0, 0));
    atlas_3().draw(backend, 267, 299, "Col B mid");
    backend.draw_border(266, 260, 266, 110, 1, rgb!(255, 255, 255));
    backend.fill_rect(266, 370, 266, 110, rgb!(0, 0, 0));
    atlas_3().draw(backend, 267, 409, "Col B bot");
    backend.draw_border(266, 370, 266, 110, 1, rgb!(255, 255, 255));
    backend.fill_rect(532, 150, 268, 110, rgb!(0, 0, 0));
    atlas_3().draw(backend, 533, 189, "Col C top");
    backend.draw_border(532, 150, 268, 110, 1, rgb!(255, 255, 255));
    backend.fill_rect(532, 260, 268, 110, rgb!(0, 0, 0));
    atlas_3().draw(backend, 533, 299, "Col C mid");
    backend.draw_border(532, 260, 268, 110, 1, rgb!(255, 255, 255));
    backend.fill_rect(532, 370, 268, 110, rgb!(0, 0, 0));
    atlas_3().draw(backend, 533, 409, "Col C bot");
    backend.draw_border(532, 370, 268, 110, 1, rgb!(255, 255, 255));
}

fn draw_complex(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    backend.fill_rect(0, 0, 800, 40, rgb!(60, 60, 60));
    atlas_1().draw(backend, 10, 10, "nested containers");
    backend.fill_rect(0, 40, 800, 50, rgb!(0, 0, 0));
    atlas_2().draw(backend, 10, 44, "Containers nest freely:");
    atlas_2().draw(backend, 10, 66, "col in row, row in col...");
    backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 106, 104, "Prev");
    backend.draw_border(104, 94, 192, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 506, 104, "Next");
    backend.draw_border(504, 94, 192, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(0, 150, 400, 165, rgb!(0, 0, 0));
    atlas_3().draw(backend, 1, 216, "Top-left");
    backend.draw_border(0, 150, 400, 165, 1, rgb!(255, 255, 255));
    backend.fill_rect(0, 315, 400, 165, rgb!(0, 0, 0));
    atlas_3().draw(backend, 1, 381, "Bottom-left");
    backend.draw_border(0, 315, 400, 165, 1, rgb!(255, 255, 255));
    backend.fill_rect(400, 150, 200, 165, rgb!(0, 0, 0));
    atlas_3().draw(backend, 401, 216, "TR-A");
    backend.draw_border(400, 150, 200, 165, 1, rgb!(255, 255, 255));
    backend.fill_rect(600, 150, 200, 165, rgb!(0, 0, 0));
    atlas_3().draw(backend, 601, 216, "TR-B");
    backend.draw_border(600, 150, 200, 165, 1, rgb!(255, 255, 255));
    backend.fill_rect(400, 315, 133, 165, rgb!(0, 0, 0));
    atlas_3().draw(backend, 401, 381, "BR-A");
    backend.draw_border(400, 315, 133, 165, 1, rgb!(255, 255, 255));
    backend.fill_rect(533, 315, 133, 165, rgb!(0, 0, 0));
    atlas_3().draw(backend, 534, 381, "BR-B");
    backend.draw_border(533, 315, 133, 165, 1, rgb!(255, 255, 255));
    backend.fill_rect(666, 315, 134, 165, rgb!(0, 0, 0));
    atlas_3().draw(backend, 667, 381, "BR-C");
    backend.draw_border(666, 315, 134, 165, 1, rgb!(255, 255, 255));
}

fn draw_dynamic(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    backend.fill_rect(0, 0, 800, 40, rgb!(60, 60, 60));
    atlas_1().draw(backend, 10, 10, "dynamic labels");
    backend.fill_rect(0, 40, 800, 50, rgb!(0, 0, 0));
    atlas_2().draw(backend, 10, 44, "lbl= cells get values via update_changes().");
    atlas_2().draw(backend, 10, 66, "They start blank; populate on first update.");
    backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 106, 104, "Prev");
    backend.draw_border(104, 94, 192, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 506, 104, "Next");
    backend.draw_border(504, 94, 192, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(0, 150, 800, 165, rgb!(0, 0, 0));
    backend.draw_border(0, 150, 800, 165, 1, rgb!(255, 255, 255));
    backend.fill_rect(0, 315, 800, 165, rgb!(0, 0, 0));
    backend.draw_border(0, 315, 800, 165, 1, rgb!(255, 255, 255));
}

fn draw_fixed(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    backend.fill_rect(0, 0, 800, 40, rgb!(60, 60, 60));
    atlas_1().draw(backend, 10, 10, "size= (fixed)");
    backend.fill_rect(0, 40, 800, 50, rgb!(0, 0, 0));
    atlas_2().draw(backend, 10, 44, "size= gives a child a fixed pixel size.");
    atlas_2().draw(backend, 10, 66, "Weighted children share the rest.");
    backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 106, 104, "Prev");
    backend.draw_border(104, 94, 192, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 506, 104, "Next");
    backend.draw_border(504, 94, 192, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(0, 150, 800, 70, rgb!(0, 0, 0));
    atlas_3().draw(backend, 1, 169, "size=70 (fixed)");
    backend.draw_border(0, 150, 800, 70, 1, rgb!(255, 255, 255));
    backend.fill_rect(0, 220, 800, 260, rgb!(0, 0, 0));
    atlas_3().draw(backend, 1, 334, "weight=2 (weighted)");
    backend.draw_border(0, 220, 800, 260, 1, rgb!(255, 255, 255));
}

fn draw_focusable(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    backend.fill_rect(0, 0, 800, 40, rgb!(60, 60, 60));
    atlas_1().draw(backend, 10, 10, "focusable=");
    backend.fill_rect(0, 40, 800, 50, rgb!(0, 0, 0));
    atlas_2().draw(backend, 10, 44, "Focused cell redraws with style.focused.");
    atlas_2().draw(backend, 10, 66, "Default: focusable iff press= is set.");
    backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 106, 104, "Prev");
    backend.draw_border(104, 94, 192, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 506, 104, "Next");
    backend.draw_border(504, 94, 192, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(0, 150, 400, 110, rgb!(0, 0, 0));
    atlas_3().draw(backend, 1, 172, "press=");
    atlas_3().draw(backend, 1, 206, "focusable=true");
    backend.draw_border(0, 150, 400, 110, 1, rgb!(255, 255, 255));
    backend.fill_rect(400, 150, 400, 110, rgb!(0, 0, 0));
    atlas_3().draw(backend, 401, 172, "press=");
    atlas_3().draw(backend, 401, 206, "focusable=false");
    backend.draw_border(400, 150, 400, 110, 1, rgb!(255, 255, 255));
    backend.fill_rect(0, 260, 400, 110, rgb!(0, 0, 0));
    atlas_3().draw(backend, 1, 282, "label");
    atlas_3().draw(backend, 1, 316, "focusable=true");
    backend.draw_border(0, 260, 400, 110, 1, rgb!(255, 255, 255));
    backend.fill_rect(400, 260, 400, 110, rgb!(0, 0, 0));
    atlas_3().draw(backend, 401, 282, "label");
    atlas_3().draw(backend, 401, 316, "focusable=false");
    backend.draw_border(400, 260, 400, 110, 1, rgb!(255, 255, 255));
    backend.fill_rect(0, 370, 400, 110, rgb!(0, 0, 0));
    atlas_3().draw(backend, 1, 392, "press=");
    atlas_3().draw(backend, 1, 426, "(default)");
    backend.draw_border(0, 370, 400, 110, 1, rgb!(255, 255, 255));
    backend.fill_rect(400, 370, 400, 110, rgb!(0, 0, 0));
    atlas_3().draw(backend, 401, 392, "label");
    atlas_3().draw(backend, 401, 426, "(default)");
    backend.draw_border(400, 370, 400, 110, 1, rgb!(255, 255, 255));
}

fn draw_hello(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    backend.fill_rect(0, 0, 800, 40, rgb!(60, 60, 60));
    atlas_1().draw(backend, 10, 10, "col layout");
    backend.fill_rect(0, 40, 800, 50, rgb!(0, 0, 0));
    atlas_2().draw(backend, 10, 44, "col stacks children vertically.");
    atlas_2().draw(backend, 10, 66, "Each child gets equal height.");
    backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 106, 104, "Prev");
    backend.draw_border(104, 94, 192, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 506, 104, "Next");
    backend.draw_border(504, 94, 192, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(0, 150, 800, 110, rgb!(60, 60, 120));
    atlas_8().draw(backend, 1, 189, "First");
    backend.draw_border(0, 150, 800, 110, 1, rgb!(255, 255, 255));
    backend.fill_rect(0, 260, 800, 110, rgb!(60, 120, 60));
    atlas_9().draw(backend, 1, 299, "Second");
    backend.draw_border(0, 260, 800, 110, 1, rgb!(255, 255, 255));
    backend.fill_rect(0, 370, 800, 110, rgb!(120, 60, 60));
    atlas_10().draw(backend, 1, 409, "Third");
    backend.draw_border(0, 370, 800, 110, 1, rgb!(255, 255, 255));
}

fn draw_margin(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    backend.fill_rect(0, 0, 800, 40, rgb!(60, 60, 60));
    atlas_1().draw(backend, 10, 10, "margin=");
    backend.fill_rect(0, 40, 800, 50, rgb!(0, 0, 0));
    atlas_2().draw(backend, 10, 44, "margin= shrinks a child from outside.");
    atlas_2().draw(backend, 10, 66, "(all four sides equally)");
    backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 106, 104, "Prev");
    backend.draw_border(104, 94, 192, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 506, 104, "Next");
    backend.draw_border(504, 94, 192, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(0, 150, 266, 330, rgb!(0, 0, 0));
    atlas_3().draw(backend, 1, 299, "margin 0");
    backend.draw_border(0, 150, 266, 330, 1, rgb!(255, 255, 255));
    backend.fill_rect(286, 170, 226, 290, rgb!(0, 0, 255));
    atlas_5().draw(backend, 287, 299, "margin 20");
    backend.draw_border(286, 170, 226, 290, 1, rgb!(255, 255, 255));
    backend.fill_rect(537, 155, 258, 320, rgb!(0, 255, 0));
    atlas_11().draw(backend, 538, 299, "margin 5");
    backend.draw_border(537, 155, 258, 320, 1, rgb!(255, 255, 255));
}

fn draw_pad(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    backend.fill_rect(0, 0, 800, 40, rgb!(60, 60, 60));
    atlas_1().draw(backend, 10, 10, "pad=");
    backend.fill_rect(0, 40, 800, 50, rgb!(0, 0, 0));
    atlas_2().draw(backend, 10, 44, "pad= adds internal space.");
    atlas_2().draw(backend, 10, 66, "pad_left/top/right/bottom: per-side.");
    backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 106, 104, "Prev");
    backend.draw_border(104, 94, 192, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 506, 104, "Next");
    backend.draw_border(504, 94, 192, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(0, 150, 266, 165, rgb!(0, 0, 0));
    atlas_3().draw(backend, 6, 216, "pad=5");
    backend.draw_border(0, 150, 266, 165, 1, rgb!(255, 255, 255));
    backend.fill_rect(266, 150, 266, 165, rgb!(0, 0, 0));
    atlas_3().draw(backend, 282, 216, "pad=15");
    backend.draw_border(266, 150, 266, 165, 1, rgb!(255, 255, 255));
    backend.fill_rect(532, 150, 268, 165, rgb!(0, 0, 0));
    atlas_3().draw(backend, 563, 216, "pad_left=30");
    backend.draw_border(532, 150, 268, 165, 1, rgb!(255, 255, 255));
    backend.fill_rect(0, 315, 266, 165, rgb!(0, 0, 0));
    atlas_3().draw(backend, 1, 391, "pad_top=20");
    backend.draw_border(0, 315, 266, 165, 1, rgb!(255, 255, 255));
    backend.fill_rect(266, 315, 266, 165, rgb!(0, 0, 0));
    atlas_3().draw(backend, 267, 381, "pad_right=20");
    backend.draw_border(266, 315, 266, 165, 1, rgb!(255, 255, 255));
    backend.fill_rect(532, 315, 268, 165, rgb!(0, 0, 0));
    atlas_3().draw(backend, 533, 371, "pad_bottom=20");
    backend.draw_border(532, 315, 268, 165, 1, rgb!(255, 255, 255));
}

fn draw_popup(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    backend.fill_rect(200, 72, 400, 40, rgb!(60, 60, 60));
    atlas_1().draw(backend, 210, 82, "popup / aligned");
    backend.fill_rect(200, 112, 400, 50, rgb!(0, 0, 0));
    atlas_2().draw(backend, 210, 116, "size={w,h}: menu size in pixels.");
    atlas_2().draw(backend, 210, 138, "align={x,y}+anchor=: position.");
    backend.fill_rect(254, 166, 92, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 256, 176, "Prev");
    backend.draw_border(254, 166, 92, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(454, 166, 92, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 456, 176, "Next");
    backend.draw_border(454, 166, 92, 52, 2, rgb!(255, 255, 255));
}

fn draw_progress(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    backend.fill_rect(0, 0, 800, 40, rgb!(60, 60, 60));
    atlas_1().draw(backend, 10, 10, "progress bar");
    backend.fill_rect(0, 40, 800, 50, rgb!(0, 0, 0));
    atlas_2().draw(backend, 10, 44, "render=\"progress bar\":");
    atlas_2().draw(backend, 10, 66, "lbl= value is a float in [0,1].");
    backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 106, 104, "Prev");
    backend.draw_border(104, 94, 192, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 506, 104, "Next");
    backend.draw_border(504, 94, 192, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(0, 150, 800, 110, rgb!(0, 0, 0));
    backend.draw_border(0, 150, 800, 110, 1, rgb!(255, 255, 255));
    backend.fill_rect(0, 260, 800, 110, rgb!(40, 40, 40));
    backend.draw_border(0, 260, 800, 110, 1, rgb!(255, 255, 255));
    backend.fill_rect(0, 370, 400, 110, rgb!(40, 40, 40));
    backend.draw_border(0, 370, 400, 110, 1, rgb!(255, 255, 255));
    backend.fill_rect(400, 370, 400, 110, rgb!(0, 0, 0));
    backend.draw_border(400, 370, 400, 110, 1, rgb!(255, 255, 255));
}

fn draw_rows(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    backend.fill_rect(0, 0, 800, 40, rgb!(60, 60, 60));
    atlas_1().draw(backend, 10, 10, "row layout");
    backend.fill_rect(0, 40, 800, 50, rgb!(0, 0, 0));
    atlas_2().draw(backend, 10, 44, "row places children side by side.");
    atlas_2().draw(backend, 10, 66, "(equal width by default)");
    backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 106, 104, "Prev");
    backend.draw_border(104, 94, 192, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 506, 104, "Next");
    backend.draw_border(504, 94, 192, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(0, 150, 266, 165, rgb!(0, 0, 0));
    atlas_3().draw(backend, 1, 216, "Left");
    backend.draw_border(0, 150, 266, 165, 1, rgb!(255, 255, 255));
    backend.fill_rect(266, 150, 266, 165, rgb!(0, 0, 0));
    atlas_3().draw(backend, 267, 216, "Center");
    backend.draw_border(266, 150, 266, 165, 1, rgb!(255, 255, 255));
    backend.fill_rect(532, 150, 268, 165, rgb!(0, 0, 0));
    atlas_3().draw(backend, 533, 216, "Right");
    backend.draw_border(532, 150, 268, 165, 1, rgb!(255, 255, 255));
    backend.fill_rect(0, 315, 200, 165, rgb!(0, 0, 0));
    atlas_3().draw(backend, 1, 381, "A");
    backend.draw_border(0, 315, 200, 165, 1, rgb!(255, 255, 255));
    backend.fill_rect(200, 315, 200, 165, rgb!(0, 0, 0));
    atlas_3().draw(backend, 201, 381, "B");
    backend.draw_border(200, 315, 200, 165, 1, rgb!(255, 255, 255));
    backend.fill_rect(400, 315, 200, 165, rgb!(0, 0, 0));
    atlas_3().draw(backend, 401, 381, "C");
    backend.draw_border(400, 315, 200, 165, 1, rgb!(255, 255, 255));
    backend.fill_rect(600, 315, 200, 165, rgb!(0, 0, 0));
    atlas_3().draw(backend, 601, 381, "D");
    backend.draw_border(600, 315, 200, 165, 1, rgb!(255, 255, 255));
}

fn draw_weighted(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    backend.fill_rect(0, 0, 800, 40, rgb!(60, 60, 60));
    atlas_1().draw(backend, 10, 10, "weight=");
    backend.fill_rect(0, 40, 800, 50, rgb!(0, 0, 0));
    atlas_2().draw(backend, 10, 44, "weight= sets proportional space.");
    atlas_2().draw(backend, 10, 66, "Default weight is 1.");
    backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 106, 104, "Prev");
    backend.draw_border(104, 94, 192, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
    atlas_4().draw(backend, 506, 104, "Next");
    backend.draw_border(504, 94, 192, 52, 2, rgb!(255, 255, 255));
    backend.fill_rect(0, 150, 133, 330, rgb!(0, 0, 0));
    atlas_3().draw(backend, 1, 299, "weight 1");
    backend.draw_border(0, 150, 133, 330, 1, rgb!(255, 255, 255));
    backend.fill_rect(133, 150, 266, 330, rgb!(0, 0, 0));
    atlas_3().draw(backend, 134, 299, "weight 2");
    backend.draw_border(133, 150, 266, 330, 1, rgb!(255, 255, 255));
    backend.fill_rect(399, 150, 401, 330, rgb!(0, 0, 0));
    atlas_3().draw(backend, 400, 299, "weight 3");
    backend.draw_border(399, 150, 401, 330, 1, rgb!(255, 255, 255));
}

fn draw_focus_borders(backend: &mut dyn Backend, focused: Option<usize>) {
    if focused == Some(0) {
        backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 114, 104, "Prev");
        backend.draw_border(104, 94, 192, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 106, 104, "Prev");
        backend.draw_border(104, 94, 192, 52, 2, rgb!(255, 255, 255));
    }
    if focused == Some(1) {
        backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 514, 104, "Next");
        backend.draw_border(504, 94, 192, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 506, 104, "Next");
        backend.draw_border(504, 94, 192, 52, 2, rgb!(255, 255, 255));
    }
}

fn draw_focus_cellstyle(backend: &mut dyn Backend, focused: Option<usize>) {
    if focused == Some(0) {
        backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 114, 104, "Prev");
        backend.draw_border(104, 94, 192, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 106, 104, "Prev");
        backend.draw_border(104, 94, 192, 52, 2, rgb!(255, 255, 255));
    }
    if focused == Some(1) {
        backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 514, 104, "Next");
        backend.draw_border(504, 94, 192, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 506, 104, "Next");
        backend.draw_border(504, 94, 192, 52, 2, rgb!(255, 255, 255));
    }
}

fn draw_focus_clickable(backend: &mut dyn Backend, focused: Option<usize>) {
    if focused == Some(0) {
        backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 114, 104, "Prev");
        backend.draw_border(104, 94, 192, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 106, 104, "Prev");
        backend.draw_border(104, 94, 192, 52, 2, rgb!(255, 255, 255));
    }
    if focused == Some(1) {
        backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 514, 104, "Next");
        backend.draw_border(504, 94, 192, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 506, 104, "Next");
        backend.draw_border(504, 94, 192, 52, 2, rgb!(255, 255, 255));
    }
    if focused == Some(2) {
        backend.fill_rect(0, 150, 800, 110, rgb!(0, 0, 0));
        atlas_3().draw(backend, 10, 189, "press={\"click\"}");
        backend.draw_border(0, 150, 800, 110, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(0, 150, 800, 110, rgb!(0, 0, 0));
        atlas_3().draw(backend, 1, 189, "press={\"click\"}");
        backend.draw_border(0, 150, 800, 110, 1, rgb!(255, 255, 255));
    }
    if focused == Some(3) {
        backend.fill_rect(0, 260, 800, 110, rgb!(0, 0, 0));
        atlas_3().draw(backend, 10, 299, "press={\"action\",\"hello\"}");
        backend.draw_border(0, 260, 800, 110, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(0, 260, 800, 110, rgb!(0, 0, 0));
        atlas_3().draw(backend, 1, 299, "press={\"action\",\"hello\"}");
        backend.draw_border(0, 260, 800, 110, 1, rgb!(255, 255, 255));
    }
    if focused == Some(4) {
        backend.fill_rect(0, 370, 800, 110, rgb!(0, 0, 0));
        atlas_3().draw(backend, 10, 409, "press={\"action\",\"a\",\"b\"}");
        backend.draw_border(0, 370, 800, 110, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(0, 370, 800, 110, rgb!(0, 0, 0));
        atlas_3().draw(backend, 1, 409, "press={\"action\",\"a\",\"b\"}");
        backend.draw_border(0, 370, 800, 110, 1, rgb!(255, 255, 255));
    }
}

fn draw_focus_cols(backend: &mut dyn Backend, focused: Option<usize>) {
    if focused == Some(0) {
        backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 114, 104, "Prev");
        backend.draw_border(104, 94, 192, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 106, 104, "Prev");
        backend.draw_border(104, 94, 192, 52, 2, rgb!(255, 255, 255));
    }
    if focused == Some(1) {
        backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 514, 104, "Next");
        backend.draw_border(504, 94, 192, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 506, 104, "Next");
        backend.draw_border(504, 94, 192, 52, 2, rgb!(255, 255, 255));
    }
}

fn draw_focus_complex(backend: &mut dyn Backend, focused: Option<usize>) {
    if focused == Some(0) {
        backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 114, 104, "Prev");
        backend.draw_border(104, 94, 192, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 106, 104, "Prev");
        backend.draw_border(104, 94, 192, 52, 2, rgb!(255, 255, 255));
    }
    if focused == Some(1) {
        backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 514, 104, "Next");
        backend.draw_border(504, 94, 192, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 506, 104, "Next");
        backend.draw_border(504, 94, 192, 52, 2, rgb!(255, 255, 255));
    }
}

fn draw_focus_dynamic(backend: &mut dyn Backend, focused: Option<usize>) {
    if focused == Some(0) {
        backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 114, 104, "Prev");
        backend.draw_border(104, 94, 192, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 106, 104, "Prev");
        backend.draw_border(104, 94, 192, 52, 2, rgb!(255, 255, 255));
    }
    if focused == Some(1) {
        backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 514, 104, "Next");
        backend.draw_border(504, 94, 192, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 506, 104, "Next");
        backend.draw_border(504, 94, 192, 52, 2, rgb!(255, 255, 255));
    }
}

fn draw_focus_fixed(backend: &mut dyn Backend, focused: Option<usize>) {
    if focused == Some(0) {
        backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 114, 104, "Prev");
        backend.draw_border(104, 94, 192, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 106, 104, "Prev");
        backend.draw_border(104, 94, 192, 52, 2, rgb!(255, 255, 255));
    }
    if focused == Some(1) {
        backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 514, 104, "Next");
        backend.draw_border(504, 94, 192, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 506, 104, "Next");
        backend.draw_border(504, 94, 192, 52, 2, rgb!(255, 255, 255));
    }
}

fn draw_focus_focusable(backend: &mut dyn Backend, focused: Option<usize>) {
    if focused == Some(0) {
        backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 114, 104, "Prev");
        backend.draw_border(104, 94, 192, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 106, 104, "Prev");
        backend.draw_border(104, 94, 192, 52, 2, rgb!(255, 255, 255));
    }
    if focused == Some(1) {
        backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 514, 104, "Next");
        backend.draw_border(504, 94, 192, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 506, 104, "Next");
        backend.draw_border(504, 94, 192, 52, 2, rgb!(255, 255, 255));
    }
    if focused == Some(2) {
        backend.fill_rect(0, 150, 400, 110, rgb!(0, 0, 0));
        atlas_3().draw(backend, 10, 172, "press=");
        atlas_3().draw(backend, 10, 206, "focusable=true");
        backend.draw_border(0, 150, 400, 110, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(0, 150, 400, 110, rgb!(0, 0, 0));
        atlas_3().draw(backend, 1, 172, "press=");
        atlas_3().draw(backend, 1, 206, "focusable=true");
        backend.draw_border(0, 150, 400, 110, 1, rgb!(255, 255, 255));
    }
    if focused == Some(3) {
        backend.fill_rect(0, 260, 400, 110, rgb!(0, 0, 0));
        atlas_3().draw(backend, 10, 282, "label");
        atlas_3().draw(backend, 10, 316, "focusable=true");
        backend.draw_border(0, 260, 400, 110, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(0, 260, 400, 110, rgb!(0, 0, 0));
        atlas_3().draw(backend, 1, 282, "label");
        atlas_3().draw(backend, 1, 316, "focusable=true");
        backend.draw_border(0, 260, 400, 110, 1, rgb!(255, 255, 255));
    }
    if focused == Some(4) {
        backend.fill_rect(0, 370, 400, 110, rgb!(0, 0, 0));
        atlas_3().draw(backend, 10, 392, "press=");
        atlas_3().draw(backend, 10, 426, "(default)");
        backend.draw_border(0, 370, 400, 110, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(0, 370, 400, 110, rgb!(0, 0, 0));
        atlas_3().draw(backend, 1, 392, "press=");
        atlas_3().draw(backend, 1, 426, "(default)");
        backend.draw_border(0, 370, 400, 110, 1, rgb!(255, 255, 255));
    }
}

fn draw_focus_hello(backend: &mut dyn Backend, focused: Option<usize>) {
    if focused == Some(0) {
        backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 114, 104, "Prev");
        backend.draw_border(104, 94, 192, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 106, 104, "Prev");
        backend.draw_border(104, 94, 192, 52, 2, rgb!(255, 255, 255));
    }
    if focused == Some(1) {
        backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 514, 104, "Next");
        backend.draw_border(504, 94, 192, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 506, 104, "Next");
        backend.draw_border(504, 94, 192, 52, 2, rgb!(255, 255, 255));
    }
}

fn draw_focus_margin(backend: &mut dyn Backend, focused: Option<usize>) {
    if focused == Some(0) {
        backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 114, 104, "Prev");
        backend.draw_border(104, 94, 192, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 106, 104, "Prev");
        backend.draw_border(104, 94, 192, 52, 2, rgb!(255, 255, 255));
    }
    if focused == Some(1) {
        backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 514, 104, "Next");
        backend.draw_border(504, 94, 192, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 506, 104, "Next");
        backend.draw_border(504, 94, 192, 52, 2, rgb!(255, 255, 255));
    }
}

fn draw_focus_pad(backend: &mut dyn Backend, focused: Option<usize>) {
    if focused == Some(0) {
        backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 114, 104, "Prev");
        backend.draw_border(104, 94, 192, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 106, 104, "Prev");
        backend.draw_border(104, 94, 192, 52, 2, rgb!(255, 255, 255));
    }
    if focused == Some(1) {
        backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 514, 104, "Next");
        backend.draw_border(504, 94, 192, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 506, 104, "Next");
        backend.draw_border(504, 94, 192, 52, 2, rgb!(255, 255, 255));
    }
}

fn draw_focus_popup(backend: &mut dyn Backend, focused: Option<usize>) {
    if focused == Some(0) {
        backend.fill_rect(254, 166, 92, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 264, 176, "Prev");
        backend.draw_border(254, 166, 92, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(254, 166, 92, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 256, 176, "Prev");
        backend.draw_border(254, 166, 92, 52, 2, rgb!(255, 255, 255));
    }
    if focused == Some(1) {
        backend.fill_rect(454, 166, 92, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 464, 176, "Next");
        backend.draw_border(454, 166, 92, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(454, 166, 92, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 456, 176, "Next");
        backend.draw_border(454, 166, 92, 52, 2, rgb!(255, 255, 255));
    }
}

fn draw_focus_progress(backend: &mut dyn Backend, focused: Option<usize>) {
    if focused == Some(0) {
        backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 114, 104, "Prev");
        backend.draw_border(104, 94, 192, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 106, 104, "Prev");
        backend.draw_border(104, 94, 192, 52, 2, rgb!(255, 255, 255));
    }
    if focused == Some(1) {
        backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 514, 104, "Next");
        backend.draw_border(504, 94, 192, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 506, 104, "Next");
        backend.draw_border(504, 94, 192, 52, 2, rgb!(255, 255, 255));
    }
}

fn draw_focus_rows(backend: &mut dyn Backend, focused: Option<usize>) {
    if focused == Some(0) {
        backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 114, 104, "Prev");
        backend.draw_border(104, 94, 192, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 106, 104, "Prev");
        backend.draw_border(104, 94, 192, 52, 2, rgb!(255, 255, 255));
    }
    if focused == Some(1) {
        backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 514, 104, "Next");
        backend.draw_border(504, 94, 192, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 506, 104, "Next");
        backend.draw_border(504, 94, 192, 52, 2, rgb!(255, 255, 255));
    }
}

fn draw_focus_weighted(backend: &mut dyn Backend, focused: Option<usize>) {
    if focused == Some(0) {
        backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 114, 104, "Prev");
        backend.draw_border(104, 94, 192, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(104, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 106, 104, "Prev");
        backend.draw_border(104, 94, 192, 52, 2, rgb!(255, 255, 255));
    }
    if focused == Some(1) {
        backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 514, 104, "Next");
        backend.draw_border(504, 94, 192, 52, 10, rgb!(255, 255, 255));
    } else {
        backend.fill_rect(504, 94, 192, 52, rgb!(30, 80, 180));
        atlas_4().draw(backend, 506, 104, "Next");
        backend.draw_border(504, 94, 192, 52, 2, rgb!(255, 255, 255));
    }
}

fn update_events_borders<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            let new_focus =
                if *x >= 104 && *x < 296 && *y >= 94 && *y < 146 { Some(0) }
                else if *x >= 504 && *x < 696 && *y >= 94 && *y < 146 { Some(1) }
                else { None };
            *FOCUSED.lock().unwrap() = new_focus;
            if *x >= 104 && *x < 296 && *y >= 94 && *y < 146 {
                state.nav(&["Margin"]);
            }
            if *x >= 504 && *x < 696 && *y >= 94 && *y < 146 {
                state.nav(&["Clickable"]);
            }
        }
    }
}

fn update_events_cellstyle<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            let new_focus =
                if *x >= 104 && *x < 296 && *y >= 94 && *y < 146 { Some(0) }
                else if *x >= 504 && *x < 696 && *y >= 94 && *y < 146 { Some(1) }
                else { None };
            *FOCUSED.lock().unwrap() = new_focus;
            if *x >= 104 && *x < 296 && *y >= 94 && *y < 146 {
                state.nav(&["Fixed"]);
            }
            if *x >= 504 && *x < 696 && *y >= 94 && *y < 146 {
                state.nav(&["Pad"]);
            }
        }
    }
}

fn update_events_clickable<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            let new_focus =
                if *x >= 104 && *x < 296 && *y >= 94 && *y < 146 { Some(0) }
                else if *x >= 504 && *x < 696 && *y >= 94 && *y < 146 { Some(1) }
                else if *x < 800 && *y >= 150 && *y < 260 { Some(2) }
                else if *x < 800 && *y >= 260 && *y < 370 { Some(3) }
                else if *x < 800 && *y >= 370 && *y < 480 { Some(4) }
                else { None };
            *FOCUSED.lock().unwrap() = new_focus;
            if *x >= 104 && *x < 296 && *y >= 94 && *y < 146 {
                state.nav(&["Borders"]);
            }
            if *x >= 504 && *x < 696 && *y >= 94 && *y < 146 {
                state.nav(&["Focusable"]);
            }
            if *x < 800 && *y >= 150 && *y < 260 {
                state.click();
            }
            if *x < 800 && *y >= 260 && *y < 370 {
                state.action(&["hello"]);
            }
            if *x < 800 && *y >= 370 && *y < 480 {
                state.action(&["a", "b"]);
            }
        }
    }
}

fn update_events_cols<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            let new_focus =
                if *x >= 104 && *x < 296 && *y >= 94 && *y < 146 { Some(0) }
                else if *x >= 504 && *x < 696 && *y >= 94 && *y < 146 { Some(1) }
                else { None };
            *FOCUSED.lock().unwrap() = new_focus;
            if *x >= 104 && *x < 296 && *y >= 94 && *y < 146 {
                state.nav(&["Rows"]);
            }
            if *x >= 504 && *x < 696 && *y >= 94 && *y < 146 {
                state.nav(&["Weighted"]);
            }
        }
    }
}

fn update_events_complex<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            let new_focus =
                if *x >= 104 && *x < 296 && *y >= 94 && *y < 146 { Some(0) }
                else if *x >= 504 && *x < 696 && *y >= 94 && *y < 146 { Some(1) }
                else { None };
            *FOCUSED.lock().unwrap() = new_focus;
            if *x >= 104 && *x < 296 && *y >= 94 && *y < 146 {
                state.nav(&["Progress"]);
            }
            if *x >= 504 && *x < 696 && *y >= 94 && *y < 146 {
                state.nav(&["Popup"]);
            }
        }
    }
}

fn update_events_dynamic<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            let new_focus =
                if *x >= 104 && *x < 296 && *y >= 94 && *y < 146 { Some(0) }
                else if *x >= 504 && *x < 696 && *y >= 94 && *y < 146 { Some(1) }
                else { None };
            *FOCUSED.lock().unwrap() = new_focus;
            if *x >= 104 && *x < 296 && *y >= 94 && *y < 146 {
                state.nav(&["Focusable"]);
            }
            if *x >= 504 && *x < 696 && *y >= 94 && *y < 146 {
                state.nav(&["Progress"]);
            }
        }
    }
}

fn update_events_fixed<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            let new_focus =
                if *x >= 104 && *x < 296 && *y >= 94 && *y < 146 { Some(0) }
                else if *x >= 504 && *x < 696 && *y >= 94 && *y < 146 { Some(1) }
                else { None };
            *FOCUSED.lock().unwrap() = new_focus;
            if *x >= 104 && *x < 296 && *y >= 94 && *y < 146 {
                state.nav(&["Weighted"]);
            }
            if *x >= 504 && *x < 696 && *y >= 94 && *y < 146 {
                state.nav(&["CellStyle"]);
            }
        }
    }
}

fn update_events_focusable<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            let new_focus =
                if *x >= 104 && *x < 296 && *y >= 94 && *y < 146 { Some(0) }
                else if *x >= 504 && *x < 696 && *y >= 94 && *y < 146 { Some(1) }
                else if *x < 400 && *y >= 150 && *y < 260 { Some(2) }
                else if *x < 400 && *y >= 260 && *y < 370 { Some(3) }
                else if *x < 400 && *y >= 370 && *y < 480 { Some(4) }
                else { None };
            *FOCUSED.lock().unwrap() = new_focus;
            if *x >= 104 && *x < 296 && *y >= 94 && *y < 146 {
                state.nav(&["Clickable"]);
            }
            if *x >= 504 && *x < 696 && *y >= 94 && *y < 146 {
                state.nav(&["Dynamic"]);
            }
            if *x < 400 && *y >= 150 && *y < 260 {
                state.click();
            }
            if *x >= 400 && *x < 800 && *y >= 150 && *y < 260 {
                state.click();
            }
            if *x < 400 && *y >= 370 && *y < 480 {
                state.click();
            }
        }
    }
}

fn update_events_hello<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            let new_focus =
                if *x >= 104 && *x < 296 && *y >= 94 && *y < 146 { Some(0) }
                else if *x >= 504 && *x < 696 && *y >= 94 && *y < 146 { Some(1) }
                else { None };
            *FOCUSED.lock().unwrap() = new_focus;
            if *x >= 104 && *x < 296 && *y >= 94 && *y < 146 {
                state.nav(&["Popup"]);
            }
            if *x >= 504 && *x < 696 && *y >= 94 && *y < 146 {
                state.nav(&["Rows"]);
            }
        }
    }
}

fn update_events_margin<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            let new_focus =
                if *x >= 104 && *x < 296 && *y >= 94 && *y < 146 { Some(0) }
                else if *x >= 504 && *x < 696 && *y >= 94 && *y < 146 { Some(1) }
                else { None };
            *FOCUSED.lock().unwrap() = new_focus;
            if *x >= 104 && *x < 296 && *y >= 94 && *y < 146 {
                state.nav(&["Pad"]);
            }
            if *x >= 504 && *x < 696 && *y >= 94 && *y < 146 {
                state.nav(&["Borders"]);
            }
        }
    }
}

fn update_events_pad<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            let new_focus =
                if *x >= 104 && *x < 296 && *y >= 94 && *y < 146 { Some(0) }
                else if *x >= 504 && *x < 696 && *y >= 94 && *y < 146 { Some(1) }
                else { None };
            *FOCUSED.lock().unwrap() = new_focus;
            if *x >= 104 && *x < 296 && *y >= 94 && *y < 146 {
                state.nav(&["CellStyle"]);
            }
            if *x >= 504 && *x < 696 && *y >= 94 && *y < 146 {
                state.nav(&["Margin"]);
            }
        }
    }
}

fn update_events_popup<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            let new_focus =
                if *x >= 254 && *x < 346 && *y >= 166 && *y < 218 { Some(0) }
                else if *x >= 454 && *x < 546 && *y >= 166 && *y < 218 { Some(1) }
                else { None };
            *FOCUSED.lock().unwrap() = new_focus;
            if *x >= 254 && *x < 346 && *y >= 166 && *y < 218 {
                state.nav(&["Complex"]);
            }
            if *x >= 454 && *x < 546 && *y >= 166 && *y < 218 {
                state.nav(&["Hello"]);
            }
        }
    }
}

fn update_events_progress<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            let new_focus =
                if *x >= 104 && *x < 296 && *y >= 94 && *y < 146 { Some(0) }
                else if *x >= 504 && *x < 696 && *y >= 94 && *y < 146 { Some(1) }
                else { None };
            *FOCUSED.lock().unwrap() = new_focus;
            if *x >= 104 && *x < 296 && *y >= 94 && *y < 146 {
                state.nav(&["Dynamic"]);
            }
            if *x >= 504 && *x < 696 && *y >= 94 && *y < 146 {
                state.nav(&["Complex"]);
            }
        }
    }
}

fn update_events_rows<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            let new_focus =
                if *x >= 104 && *x < 296 && *y >= 94 && *y < 146 { Some(0) }
                else if *x >= 504 && *x < 696 && *y >= 94 && *y < 146 { Some(1) }
                else { None };
            *FOCUSED.lock().unwrap() = new_focus;
            if *x >= 104 && *x < 296 && *y >= 94 && *y < 146 {
                state.nav(&["Hello"]);
            }
            if *x >= 504 && *x < 696 && *y >= 94 && *y < 146 {
                state.nav(&["Cols"]);
            }
        }
    }
}

fn update_events_weighted<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            let new_focus =
                if *x >= 104 && *x < 296 && *y >= 94 && *y < 146 { Some(0) }
                else if *x >= 504 && *x < 696 && *y >= 94 && *y < 146 { Some(1) }
                else { None };
            *FOCUSED.lock().unwrap() = new_focus;
            if *x >= 104 && *x < 296 && *y >= 94 && *y < 146 {
                state.nav(&["Cols"]);
            }
            if *x >= 504 && *x < 696 && *y >= 94 && *y < 146 {
                state.nav(&["Fixed"]);
            }
        }
    }
}

fn update_changes_borders(backend: &mut dyn Backend, _changes: &[(&str, &str)]) {
    {
        let focused = *FOCUSED.lock().unwrap();
        let mut last = LAST_DRAWN_FOCUS.lock().unwrap();
        if *last != focused {
            *last = focused;
            drop(last);
            draw_focus_borders(backend, focused);
        }
    }
}

fn update_changes_cellstyle(backend: &mut dyn Backend, _changes: &[(&str, &str)]) {
    {
        let focused = *FOCUSED.lock().unwrap();
        let mut last = LAST_DRAWN_FOCUS.lock().unwrap();
        if *last != focused {
            *last = focused;
            drop(last);
            draw_focus_cellstyle(backend, focused);
        }
    }
}

fn update_changes_clickable(backend: &mut dyn Backend, _changes: &[(&str, &str)]) {
    {
        let focused = *FOCUSED.lock().unwrap();
        let mut last = LAST_DRAWN_FOCUS.lock().unwrap();
        if *last != focused {
            *last = focused;
            drop(last);
            draw_focus_clickable(backend, focused);
        }
    }
}

fn update_changes_cols(backend: &mut dyn Backend, _changes: &[(&str, &str)]) {
    {
        let focused = *FOCUSED.lock().unwrap();
        let mut last = LAST_DRAWN_FOCUS.lock().unwrap();
        if *last != focused {
            *last = focused;
            drop(last);
            draw_focus_cols(backend, focused);
        }
    }
}

fn update_changes_complex(backend: &mut dyn Backend, _changes: &[(&str, &str)]) {
    {
        let focused = *FOCUSED.lock().unwrap();
        let mut last = LAST_DRAWN_FOCUS.lock().unwrap();
        if *last != focused {
            *last = focused;
            drop(last);
            draw_focus_complex(backend, focused);
        }
    }
}

fn update_changes_dynamic(backend: &mut dyn Backend, changes: &[(&str, &str)]) {
    if changes.iter().any(|&(n, _)| n == "parameter One" || n == "parameter Two") {
        backend.render(&mut |fb, stride| {
            for &(name, val) in changes {
                match name {
                    "parameter One" => atlas_3().blit(fb, stride, 1, 216,
                        &format!("{:<46}", val)),
                    "parameter Two" => atlas_3().blit(fb, stride, 1, 381,
                        &format!("{:<46}", val)),
                    _ => {}
                }
            }
        });
    }
    {
        let focused = *FOCUSED.lock().unwrap();
        let mut last = LAST_DRAWN_FOCUS.lock().unwrap();
        if *last != focused {
            *last = focused;
            drop(last);
            draw_focus_dynamic(backend, focused);
        }
    }
}

fn update_changes_fixed(backend: &mut dyn Backend, _changes: &[(&str, &str)]) {
    {
        let focused = *FOCUSED.lock().unwrap();
        let mut last = LAST_DRAWN_FOCUS.lock().unwrap();
        if *last != focused {
            *last = focused;
            drop(last);
            draw_focus_fixed(backend, focused);
        }
    }
}

fn update_changes_focusable(backend: &mut dyn Backend, _changes: &[(&str, &str)]) {
    {
        let focused = *FOCUSED.lock().unwrap();
        let mut last = LAST_DRAWN_FOCUS.lock().unwrap();
        if *last != focused {
            *last = focused;
            drop(last);
            draw_focus_focusable(backend, focused);
        }
    }
}

fn update_changes_hello(backend: &mut dyn Backend, _changes: &[(&str, &str)]) {
    {
        let focused = *FOCUSED.lock().unwrap();
        let mut last = LAST_DRAWN_FOCUS.lock().unwrap();
        if *last != focused {
            *last = focused;
            drop(last);
            draw_focus_hello(backend, focused);
        }
    }
}

fn update_changes_margin(backend: &mut dyn Backend, _changes: &[(&str, &str)]) {
    {
        let focused = *FOCUSED.lock().unwrap();
        let mut last = LAST_DRAWN_FOCUS.lock().unwrap();
        if *last != focused {
            *last = focused;
            drop(last);
            draw_focus_margin(backend, focused);
        }
    }
}

fn update_changes_pad(backend: &mut dyn Backend, _changes: &[(&str, &str)]) {
    {
        let focused = *FOCUSED.lock().unwrap();
        let mut last = LAST_DRAWN_FOCUS.lock().unwrap();
        if *last != focused {
            *last = focused;
            drop(last);
            draw_focus_pad(backend, focused);
        }
    }
}

fn update_changes_popup(backend: &mut dyn Backend, _changes: &[(&str, &str)]) {
    {
        let focused = *FOCUSED.lock().unwrap();
        let mut last = LAST_DRAWN_FOCUS.lock().unwrap();
        if *last != focused {
            *last = focused;
            drop(last);
            draw_focus_popup(backend, focused);
        }
    }
}

fn update_changes_progress(backend: &mut dyn Backend, changes: &[(&str, &str)]) {
    if changes.iter().any(|&(n, _)| n == "parameter One") {
        backend.render(&mut |fb, stride| {
            for &(name, val) in changes {
                if name == "parameter One" {
                    atlas_3().blit(fb, stride, 401, 409,
                        &format!("{:<23}", val));
                }
            }
        });
    }
    for &(name, val) in changes {
        if name == "parameter One" {
            if let Ok(v) = val.parse::<f32>() {
                let v = v.clamp(0.0, 1.0);
                let filled = (798.0_f32 * v) as usize;
                let prev = PROG_1_PREV.swap(filled, Ordering::Relaxed);
                if filled != prev {
                    if prev == usize::MAX {
                        if filled > 0 { backend.fill_rect(1, 151, filled, 108, rgb!(255, 255, 255)); }
                        if filled < 798 { backend.fill_rect(1 + filled, 151, 798 - filled, 108, rgb!(0, 0, 0)); }
                    } else if filled > prev {
                        backend.fill_rect(1 + prev, 151, filled - prev, 108, rgb!(255, 255, 255));
                    } else {
                        backend.fill_rect(1 + filled, 151, prev - filled, 108, rgb!(0, 0, 0));
                    }
                }
            }
        }
        if name == "parameter One" {
            if let Ok(v) = val.parse::<f32>() {
                let v = v.clamp(0.0, 1.0);
                let filled = (782.0_f32 * v) as usize;
                let prev = PROG_2_PREV.swap(filled, Ordering::Relaxed);
                if filled != prev {
                    if prev == usize::MAX {
                        if filled > 0 { backend.fill_rect(9, 269, filled, 92, rgb!(0, 255, 0)); }
                        if filled < 782 { backend.fill_rect(9 + filled, 269, 782 - filled, 92, rgb!(40, 40, 40)); }
                    } else if filled > prev {
                        backend.fill_rect(9 + prev, 269, filled - prev, 92, rgb!(0, 255, 0));
                    } else {
                        backend.fill_rect(9 + filled, 269, prev - filled, 92, rgb!(40, 40, 40));
                    }
                }
            }
        }
        if name == "parameter One" {
            if let Ok(v) = val.parse::<f32>() {
                let v = v.clamp(0.0, 1.0);
                let filled = (382.0_f32 * v) as usize;
                let prev = PROG_3_PREV.swap(filled, Ordering::Relaxed);
                if filled != prev {
                    if prev == usize::MAX {
                        if filled > 0 { backend.fill_rect(9, 379, filled, 92, rgb!(0, 255, 0)); }
                        if filled < 382 { backend.fill_rect(9 + filled, 379, 382 - filled, 92, rgb!(40, 40, 40)); }
                    } else if filled > prev {
                        backend.fill_rect(9 + prev, 379, filled - prev, 92, rgb!(0, 255, 0));
                    } else {
                        backend.fill_rect(9 + filled, 379, prev - filled, 92, rgb!(40, 40, 40));
                    }
                }
            }
        }
    }
    {
        let focused = *FOCUSED.lock().unwrap();
        let mut last = LAST_DRAWN_FOCUS.lock().unwrap();
        if *last != focused {
            *last = focused;
            drop(last);
            draw_focus_progress(backend, focused);
        }
    }
}

fn update_changes_rows(backend: &mut dyn Backend, _changes: &[(&str, &str)]) {
    {
        let focused = *FOCUSED.lock().unwrap();
        let mut last = LAST_DRAWN_FOCUS.lock().unwrap();
        if *last != focused {
            *last = focused;
            drop(last);
            draw_focus_rows(backend, focused);
        }
    }
}

fn update_changes_weighted(backend: &mut dyn Backend, _changes: &[(&str, &str)]) {
    {
        let focused = *FOCUSED.lock().unwrap();
        let mut last = LAST_DRAWN_FOCUS.lock().unwrap();
        if *last != focused {
            *last = focused;
            drop(last);
            draw_focus_weighted(backend, focused);
        }
    }
}

