// Generated by scripts/layout.lua — do not edit.
// Re-run the transpiler to update:
//   lua scripts/layout.lua < examples/ui.lua > examples/app/ui.rs
// transpiler: 59c3881ae0f4c03bdb044eb9e91117f45f8538ef66b646846902d793c64ea10f
// input:      35acb90e7b856acc3375714420bfcd37b78c3ea3e5436d53f229c9bbabae80d2

use imgrids::{rgb, Backend, InputEvent, Renderer};
use imgrids::ttf::TtfAtlas;
use std::sync::OnceLock;
use std::sync::Mutex;

static ATLAS_1: OnceLock<TtfAtlas> = OnceLock::new();
fn atlas_1() -> &'static TtfAtlas {
    ATLAS_1.get_or_init(|| TtfAtlas::new("fonts/RobotoMono-Regular.ttf", 32, rgb!(255, 255, 255), rgb!(0, 0, 0))
        .expect("fonts/RobotoMono-Regular.ttf"))
}

static ATLAS_2: OnceLock<TtfAtlas> = OnceLock::new();
fn atlas_2() -> &'static TtfAtlas {
    ATLAS_2.get_or_init(|| TtfAtlas::new("fonts/RobotoMono-Regular.ttf", 32, rgb!(255, 255, 255), rgb!(0, 255, 0))
        .expect("fonts/RobotoMono-Regular.ttf"))
}

static ATLAS_3: OnceLock<TtfAtlas> = OnceLock::new();
fn atlas_3() -> &'static TtfAtlas {
    ATLAS_3.get_or_init(|| TtfAtlas::new("fonts/MyriadPro-Regular.ttf", 24, rgb!(255, 255, 255), rgb!(0, 255, 0))
        .expect("fonts/MyriadPro-Regular.ttf"))
}

#[derive(Clone, Copy, PartialEq)]
pub enum Menu {
    Borders,
    Clickable,
    Complex,
    DynStat,
    Grid,
    Margin,
    Pad,
    Popup,
    Simple,
    Styled,
    SubStyled,
    Unequal,
    Widget,
}

static CURRENT_MENU: Mutex<Option<Menu>> = Mutex::new(None);

pub trait Callbacks {
    fn quit(&mut self);
    fn click(&mut self);
    fn fn3(&mut self);
    fn fn_multi(&mut self, args: &[&str]);
    fn function_cl(&mut self);
    fn function_pr(&mut self, args: &[&str]);
    fn nav(&mut self, args: &[&str]);
}

pub fn to_menu(name: &str) -> Option<Menu> {
    match name {
        "Borders" => Some(Menu::Borders),
        "Clickable" => Some(Menu::Clickable),
        "Complex" => Some(Menu::Complex),
        "DynStat" => Some(Menu::DynStat),
        "Grid" => Some(Menu::Grid),
        "Margin" => Some(Menu::Margin),
        "Pad" => Some(Menu::Pad),
        "Popup" => Some(Menu::Popup),
        "Simple" => Some(Menu::Simple),
        "Styled" => Some(Menu::Styled),
        "SubStyled" => Some(Menu::SubStyled),
        "Unequal" => Some(Menu::Unequal),
        "Widget" => Some(Menu::Widget),
        _ => None,
    }
}

pub fn update_events<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Quit = ev { state.quit(); return; }
    }
    match *CURRENT_MENU.lock().unwrap() {
        Some(Menu::Borders) => update_events_borders(events, state),
        Some(Menu::Clickable) => update_events_clickable(events, state),
        Some(Menu::Complex) => update_events_complex(events, state),
        Some(Menu::DynStat) => update_events_dynstat(events, state),
        Some(Menu::Grid) => update_events_grid(events, state),
        Some(Menu::Margin) => update_events_margin(events, state),
        Some(Menu::Pad) => update_events_pad(events, state),
        Some(Menu::Popup) => update_events_popup(events, state),
        Some(Menu::Simple) => update_events_simple(events, state),
        Some(Menu::Styled) => update_events_styled(events, state),
        Some(Menu::SubStyled) => update_events_substyled(events, state),
        Some(Menu::Unequal) => update_events_unequal(events, state),
        Some(Menu::Widget) => update_events_widget(events, state),
        None => {}
    }
}

pub fn update_menu(backend: &mut dyn Backend, menu: Menu) {
    let mut current = CURRENT_MENU.lock().unwrap();
    if *current != Some(menu) {
        *current = Some(menu);
        drop(current);
        match menu {
            Menu::Borders => draw_borders(backend),
            Menu::Clickable => draw_clickable(backend),
            Menu::Complex => draw_complex(backend),
            Menu::DynStat => draw_dynstat(backend),
            Menu::Grid => draw_grid(backend),
            Menu::Margin => draw_margin(backend),
            Menu::Pad => draw_pad(backend),
            Menu::Popup => draw_popup(backend),
            Menu::Simple => draw_simple(backend),
            Menu::Styled => draw_styled(backend),
            Menu::SubStyled => draw_substyled(backend),
            Menu::Unequal => draw_unequal(backend),
            Menu::Widget => draw_widget(backend),
        }
    }
}

pub fn update_changes(backend: &mut dyn Backend, changes: &[(&str, &str)]) {
    match *CURRENT_MENU.lock().unwrap() {
        Some(Menu::Borders) => update_changes_borders(backend, changes),
        Some(Menu::Clickable) => update_changes_clickable(backend, changes),
        Some(Menu::Complex) => update_changes_complex(backend, changes),
        Some(Menu::DynStat) => update_changes_dynstat(backend, changes),
        Some(Menu::Grid) => update_changes_grid(backend, changes),
        Some(Menu::Margin) => update_changes_margin(backend, changes),
        Some(Menu::Pad) => update_changes_pad(backend, changes),
        Some(Menu::Popup) => update_changes_popup(backend, changes),
        Some(Menu::Simple) => update_changes_simple(backend, changes),
        Some(Menu::Styled) => update_changes_styled(backend, changes),
        Some(Menu::SubStyled) => update_changes_substyled(backend, changes),
        Some(Menu::Unequal) => update_changes_unequal(backend, changes),
        Some(Menu::Widget) => update_changes_widget(backend, changes),
        None => {}
    }
}

fn draw_borders(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    atlas_1().draw(backend, 15, 36, "Prev");
    backend.draw_border(10, 10, 390, 84, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 405, 36, "Next");
    backend.draw_border(400, 10, 390, 84, 5, rgb!(255, 255, 255));
    backend.draw_border(5, 5, 790, 94, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 11, 130, "Label One");
    backend.draw_border(8, 102, 392, 88, 3, rgb!(0, 255, 0));
    atlas_1().draw(backend, 403, 130, "Label Two");
    backend.draw_border(400, 102, 392, 88, 3, rgb!(0, 255, 0));
    backend.draw_border(5, 99, 790, 94, 3, rgb!(0, 255, 0));
    atlas_1().draw(backend, 15, 224, "Label Three");
    backend.draw_border(10, 198, 390, 84, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 402, 224, "Label Four");
    backend.draw_border(400, 198, 390, 84, 2, rgb!(255, 255, 255));
    backend.draw_border(5, 193, 790, 94, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 5, 321, "Label Five");
    backend.fill_rect(5, 290, 790, 3, rgb!(255, 255, 255));
    backend.fill_rect(5, 287, 790, 3, rgb!(255, 255, 255));
    atlas_2().draw(backend, 15, 412, "Label Seven");
    backend.draw_border(10, 386, 780, 84, 5, rgb!(255, 255, 255));
    backend.draw_border(5, 381, 790, 94, 5, rgb!(255, 255, 255));
    backend.draw_border(0, 0, 800, 480, 5, rgb!(255, 255, 255));
}

fn draw_clickable(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    atlas_1().draw(backend, 15, 36, "Prev");
    backend.draw_border(10, 10, 390, 84, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 405, 36, "Next");
    backend.draw_border(400, 10, 390, 84, 5, rgb!(255, 255, 255));
    backend.draw_border(5, 5, 790, 94, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 10, 130, "Click me!");
    backend.draw_border(5, 99, 790, 94, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 10, 224, "Press me!");
    backend.draw_border(5, 193, 790, 94, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 10, 318, "Touch me!");
    backend.draw_border(5, 287, 790, 94, 5, rgb!(255, 255, 255));
    backend.fill_rect(5, 381, 790, 94, rgb!(0, 0, 0));
    backend.draw_border(5, 381, 790, 94, 5, rgb!(255, 255, 255));
    backend.draw_border(0, 0, 800, 480, 5, rgb!(255, 255, 255));
}

fn draw_complex(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    atlas_1().draw(backend, 15, 106, "Prev");
    backend.draw_border(10, 10, 390, 225, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 405, 106, "Next");
    backend.draw_border(400, 10, 390, 225, 5, rgb!(255, 255, 255));
    backend.draw_border(5, 5, 790, 235, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 20, 287, "Label One");
    backend.draw_border(15, 250, 380, 107, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 20, 395, "Label Two");
    backend.draw_border(15, 357, 380, 108, 5, rgb!(255, 255, 255));
    backend.draw_border(10, 245, 390, 225, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 415, 269, "Label Three");
    backend.draw_border(410, 255, 185, 61, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 600, 269, "Label Four");
    backend.draw_border(595, 255, 185, 61, 5, rgb!(255, 255, 255));
    backend.draw_border(405, 250, 380, 71, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 415, 340, "Label Five");
    backend.draw_border(410, 326, 123, 61, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 538, 340, "Label Six");
    backend.draw_border(533, 326, 123, 61, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 661, 340, "Label Seven");
    backend.draw_border(656, 326, 124, 61, 5, rgb!(255, 255, 255));
    backend.draw_border(405, 321, 380, 71, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 415, 412, "Click!");
    backend.draw_border(410, 397, 370, 63, 5, rgb!(255, 255, 255));
    backend.draw_border(405, 392, 380, 73, 5, rgb!(255, 255, 255));
    backend.draw_border(400, 245, 390, 225, 5, rgb!(255, 255, 255));
    backend.draw_border(5, 240, 790, 235, 5, rgb!(255, 255, 255));
    backend.draw_border(0, 0, 800, 480, 5, rgb!(255, 255, 255));
}

fn draw_dynstat(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    atlas_1().draw(backend, 15, 67, "Prev");
    backend.draw_border(10, 10, 390, 146, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 405, 67, "Next");
    backend.draw_border(400, 10, 390, 146, 5, rgb!(255, 255, 255));
    backend.draw_border(5, 5, 790, 156, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 10, 223, "Simple Label");
    backend.draw_border(5, 161, 790, 156, 5, rgb!(255, 255, 255));
    backend.fill_rect(5, 317, 790, 158, rgb!(0, 0, 0));
    backend.draw_border(5, 317, 790, 158, 5, rgb!(255, 255, 255));
    backend.draw_border(0, 0, 800, 480, 5, rgb!(255, 255, 255));
}

fn draw_grid(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    atlas_1().draw(backend, 15, 67, "Prev");
    backend.draw_border(10, 10, 390, 146, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 405, 67, "Next");
    backend.draw_border(400, 10, 390, 146, 5, rgb!(255, 255, 255));
    backend.draw_border(5, 5, 790, 156, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 15, 223, "Label One");
    backend.draw_border(10, 166, 390, 146, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 405, 223, "Label Two");
    backend.draw_border(400, 166, 390, 146, 5, rgb!(255, 255, 255));
    backend.draw_border(5, 161, 790, 156, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 15, 380, "Label Three");
    backend.draw_border(10, 322, 390, 148, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 405, 380, "Label Four");
    backend.draw_border(400, 322, 390, 148, 5, rgb!(255, 255, 255));
    backend.draw_border(5, 317, 790, 158, 5, rgb!(255, 255, 255));
    backend.draw_border(0, 0, 800, 480, 5, rgb!(255, 255, 255));
}

fn draw_margin(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    atlas_1().draw(backend, 30, 51, "Prev");
    backend.draw_border(25, 25, 370, 85, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 410, 51, "Next");
    backend.draw_border(405, 25, 370, 85, 5, rgb!(255, 255, 255));
    backend.draw_border(15, 15, 770, 105, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 30, 166, "Label One");
    backend.draw_border(25, 140, 370, 85, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 410, 166, "Label Two");
    backend.draw_border(405, 140, 370, 85, 5, rgb!(255, 255, 255));
    backend.draw_border(15, 130, 770, 105, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 30, 281, "Label Three");
    backend.draw_border(25, 255, 370, 85, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 410, 281, "Label Four");
    backend.draw_border(405, 255, 370, 85, 5, rgb!(255, 255, 255));
    backend.draw_border(15, 245, 770, 105, 5, rgb!(255, 255, 255));
    atlas_2().draw(backend, 30, 396, "Label Five");
    backend.draw_border(25, 370, 750, 85, 5, rgb!(255, 255, 255));
    backend.draw_border(15, 360, 770, 105, 5, rgb!(255, 255, 255));
    backend.draw_border(5, 5, 790, 470, 5, rgb!(255, 255, 255));
}

fn draw_pad(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    atlas_1().draw(backend, 35, 74, "Prev");
    backend.draw_border(30, 30, 370, 120, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 405, 74, "Next");
    backend.draw_border(400, 30, 370, 120, 5, rgb!(255, 255, 255));
    backend.draw_border(15, 15, 770, 150, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 35, 224, "Label One");
    backend.draw_border(30, 180, 370, 120, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 405, 224, "Label Two");
    backend.draw_border(400, 180, 370, 120, 5, rgb!(255, 255, 255));
    backend.draw_border(15, 165, 770, 150, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 35, 374, "Label Three");
    backend.draw_border(30, 330, 370, 120, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 405, 374, "Label Four");
    backend.draw_border(400, 330, 370, 120, 5, rgb!(255, 255, 255));
    backend.draw_border(15, 315, 770, 150, 5, rgb!(255, 255, 255));
    backend.draw_border(0, 0, 800, 480, 5, rgb!(255, 255, 255));
}

fn draw_popup(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    atlas_1().draw(backend, 215, 84, "Prev");
    backend.draw_border(210, 70, 190, 60, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 405, 84, "Next");
    backend.draw_border(400, 70, 190, 60, 5, rgb!(255, 255, 255));
    backend.draw_border(205, 65, 390, 70, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 215, 154, "Label One");
    backend.draw_border(210, 140, 190, 60, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 405, 154, "Label Two");
    backend.draw_border(400, 140, 190, 60, 5, rgb!(255, 255, 255));
    backend.draw_border(205, 135, 390, 70, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 215, 224, "Label Three");
    backend.draw_border(210, 210, 190, 60, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 405, 224, "Label Four");
    backend.draw_border(400, 210, 190, 60, 5, rgb!(255, 255, 255));
    backend.draw_border(205, 205, 390, 70, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 215, 294, "Label Five");
    backend.draw_border(210, 280, 190, 60, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 405, 294, "Label Six");
    backend.draw_border(400, 280, 190, 60, 5, rgb!(255, 255, 255));
    backend.draw_border(205, 275, 390, 70, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 215, 364, "Label Seven");
    backend.draw_border(210, 350, 190, 60, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 405, 364, "Label Eight");
    backend.draw_border(400, 350, 190, 60, 5, rgb!(255, 255, 255));
    backend.draw_border(205, 345, 390, 70, 5, rgb!(255, 255, 255));
    backend.draw_border(200, 60, 400, 360, 5, rgb!(255, 255, 255));
}

fn draw_simple(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    atlas_1().draw(backend, 15, 36, "Prev");
    backend.draw_border(10, 10, 390, 84, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 405, 36, "Next");
    backend.draw_border(400, 10, 390, 84, 5, rgb!(255, 255, 255));
    backend.draw_border(5, 5, 790, 94, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 10, 130, "Item One");
    backend.draw_border(5, 99, 790, 94, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 10, 224, "Item Two");
    backend.draw_border(5, 193, 790, 94, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 10, 318, "Item One");
    backend.draw_border(5, 287, 790, 94, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 10, 412, "More Text");
    backend.draw_border(5, 381, 790, 94, 5, rgb!(255, 255, 255));
    backend.draw_border(0, 0, 800, 480, 5, rgb!(255, 255, 255));
}

fn draw_styled(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    atlas_2().draw(backend, 15, 67, "Prev");
    backend.draw_border(10, 10, 390, 146, 5, rgb!(255, 255, 255));
    atlas_2().draw(backend, 405, 67, "Next");
    backend.draw_border(400, 10, 390, 146, 5, rgb!(255, 255, 255));
    backend.draw_border(5, 5, 790, 156, 5, rgb!(255, 255, 255));
    atlas_2().draw(backend, 15, 223, "Label One");
    backend.draw_border(10, 166, 390, 146, 5, rgb!(255, 255, 255));
    atlas_2().draw(backend, 405, 223, "Label Two");
    backend.draw_border(400, 166, 390, 146, 5, rgb!(255, 255, 255));
    backend.draw_border(5, 161, 790, 156, 5, rgb!(255, 255, 255));
    atlas_2().draw(backend, 15, 380, "Label Three");
    backend.draw_border(10, 322, 390, 148, 5, rgb!(255, 255, 255));
    atlas_2().draw(backend, 405, 380, "Label Four");
    backend.draw_border(400, 322, 390, 148, 5, rgb!(255, 255, 255));
    backend.draw_border(5, 317, 790, 158, 5, rgb!(255, 255, 255));
    backend.draw_border(0, 0, 800, 480, 5, rgb!(255, 255, 255));
}

fn draw_substyled(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    atlas_2().draw(backend, 15, 67, "Prev");
    backend.draw_border(10, 10, 390, 146, 5, rgb!(255, 255, 255));
    atlas_2().draw(backend, 405, 67, "Next");
    backend.draw_border(400, 10, 390, 146, 5, rgb!(255, 255, 255));
    backend.draw_border(5, 5, 790, 156, 5, rgb!(255, 255, 255));
    atlas_2().draw(backend, 15, 223, "Label One");
    backend.draw_border(10, 166, 390, 146, 5, rgb!(255, 255, 255));
    atlas_2().draw(backend, 405, 223, "Label Two");
    backend.draw_border(400, 166, 390, 146, 5, rgb!(255, 255, 255));
    backend.draw_border(5, 161, 790, 156, 5, rgb!(255, 255, 255));
    atlas_3().draw(backend, 15, 384, "Label Three");
    backend.draw_border(10, 322, 390, 148, 5, rgb!(255, 255, 255));
    atlas_2().draw(backend, 405, 380, "Label Four");
    backend.draw_border(400, 322, 390, 148, 5, rgb!(255, 255, 255));
    backend.draw_border(5, 317, 790, 158, 5, rgb!(255, 255, 255));
    backend.draw_border(0, 0, 800, 480, 5, rgb!(255, 255, 255));
}

fn draw_unequal(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    atlas_1().draw(backend, 15, 22, "Prev");
    backend.draw_border(10, 10, 390, 57, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 405, 22, "Next");
    backend.draw_border(400, 10, 390, 57, 5, rgb!(255, 255, 255));
    backend.draw_border(5, 5, 790, 67, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 15, 89, "Label One");
    backend.draw_border(10, 77, 390, 57, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 405, 89, "Label Two");
    backend.draw_border(400, 77, 390, 57, 5, rgb!(255, 255, 255));
    backend.draw_border(5, 72, 790, 67, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 15, 223, "Label Three");
    backend.draw_border(10, 144, 390, 191, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 405, 223, "Label Four");
    backend.draw_border(400, 144, 390, 191, 5, rgb!(255, 255, 255));
    backend.draw_border(5, 139, 790, 201, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 15, 391, "Label Five");
    backend.draw_border(10, 345, 390, 125, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 405, 391, "Label Six");
    backend.draw_border(400, 345, 390, 125, 5, rgb!(255, 255, 255));
    backend.draw_border(5, 340, 790, 135, 5, rgb!(255, 255, 255));
    backend.draw_border(0, 0, 800, 480, 5, rgb!(255, 255, 255));
}

fn draw_widget(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    atlas_1().draw(backend, 15, 47, "Prev");
    backend.draw_border(10, 10, 390, 107, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 405, 47, "Next");
    backend.draw_border(400, 10, 390, 107, 5, rgb!(255, 255, 255));
    backend.draw_border(5, 5, 790, 117, 5, rgb!(255, 255, 255));
    atlas_1().draw(backend, 10, 164, "Simple Label");
    backend.draw_border(5, 122, 790, 117, 5, rgb!(255, 255, 255));
    backend.fill_rect(5, 239, 790, 117, rgb!(0, 0, 0));
    backend.draw_border(5, 239, 790, 117, 5, rgb!(255, 255, 255));
    backend.fill_rect(5, 356, 790, 119, rgb!(0, 0, 0));
    backend.draw_border(5, 356, 790, 119, 5, rgb!(255, 255, 255));
    backend.draw_border(0, 0, 800, 480, 5, rgb!(255, 255, 255));
}

fn update_events_borders<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            if *x >= 10 && *x < 400 && *y >= 10 && *y < 94 {
                state.nav(&["Widget"]);
            }
            if *x >= 400 && *x < 790 && *y >= 10 && *y < 94 {
                state.nav(&["Clickable"]);
            }
        }
    }
}

fn update_events_clickable<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            if *x >= 10 && *x < 400 && *y >= 10 && *y < 94 {
                state.nav(&["Borders"]);
            }
            if *x >= 400 && *x < 790 && *y >= 10 && *y < 94 {
                state.nav(&["Complex"]);
            }
            if *x >= 5 && *x < 795 && *y >= 99 && *y < 193 {
                state.function_cl();
            }
            if *x >= 5 && *x < 795 && *y >= 193 && *y < 287 {
                state.function_pr(&["hello"]);
            }
            if *x >= 5 && *x < 795 && *y >= 287 && *y < 381 {
                state.fn_multi(&["a", "b"]);
            }
            if *x >= 5 && *x < 795 && *y >= 381 && *y < 475 {
                state.fn3();
            }
        }
    }
}

fn update_events_complex<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            if *x >= 10 && *x < 400 && *y >= 10 && *y < 235 {
                state.nav(&["Clickable"]);
            }
            if *x >= 400 && *x < 790 && *y >= 10 && *y < 235 {
                state.nav(&["DynStat"]);
            }
            if *x >= 405 && *x < 785 && *y >= 392 && *y < 465 {
                state.click();
            }
        }
    }
}

fn update_events_dynstat<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            if *x >= 10 && *x < 400 && *y >= 10 && *y < 156 {
                state.nav(&["Complex"]);
            }
            if *x >= 400 && *x < 790 && *y >= 10 && *y < 156 {
                state.nav(&["Grid"]);
            }
        }
    }
}

fn update_events_grid<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            if *x >= 10 && *x < 400 && *y >= 10 && *y < 156 {
                state.nav(&["DynStat"]);
            }
            if *x >= 400 && *x < 790 && *y >= 10 && *y < 156 {
                state.nav(&["Margin"]);
            }
        }
    }
}

fn update_events_margin<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            if *x >= 25 && *x < 395 && *y >= 25 && *y < 110 {
                state.nav(&["Grid"]);
            }
            if *x >= 405 && *x < 775 && *y >= 25 && *y < 110 {
                state.nav(&["Pad"]);
            }
        }
    }
}

fn update_events_pad<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            if *x >= 30 && *x < 400 && *y >= 30 && *y < 150 {
                state.nav(&["Margin"]);
            }
            if *x >= 400 && *x < 770 && *y >= 30 && *y < 150 {
                state.nav(&["Popup"]);
            }
        }
    }
}

fn update_events_popup<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            if *x >= 210 && *x < 400 && *y >= 70 && *y < 130 {
                state.nav(&["Pad"]);
            }
            if *x >= 400 && *x < 590 && *y >= 70 && *y < 130 {
                state.nav(&["Simple"]);
            }
        }
    }
}

fn update_events_simple<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            if *x >= 10 && *x < 400 && *y >= 10 && *y < 94 {
                state.nav(&["Popup"]);
            }
            if *x >= 400 && *x < 790 && *y >= 10 && *y < 94 {
                state.nav(&["Styled"]);
            }
        }
    }
}

fn update_events_styled<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            if *x >= 10 && *x < 400 && *y >= 10 && *y < 156 {
                state.nav(&["Simple"]);
            }
            if *x >= 400 && *x < 790 && *y >= 10 && *y < 156 {
                state.nav(&["SubStyled"]);
            }
        }
    }
}

fn update_events_substyled<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            if *x >= 10 && *x < 400 && *y >= 10 && *y < 156 {
                state.nav(&["Styled"]);
            }
            if *x >= 400 && *x < 790 && *y >= 10 && *y < 156 {
                state.nav(&["Unequal"]);
            }
        }
    }
}

fn update_events_unequal<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            if *x >= 10 && *x < 400 && *y >= 10 && *y < 67 {
                state.nav(&["SubStyled"]);
            }
            if *x >= 400 && *x < 790 && *y >= 10 && *y < 67 {
                state.nav(&["Widget"]);
            }
        }
    }
}

fn update_events_widget<C: Callbacks>(events: &[InputEvent], state: &mut C) {
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            if *x >= 10 && *x < 400 && *y >= 10 && *y < 117 {
                state.nav(&["Unequal"]);
            }
            if *x >= 400 && *x < 790 && *y >= 10 && *y < 117 {
                state.nav(&["Borders"]);
            }
        }
    }
}

fn update_changes_borders(_backend: &mut dyn Backend, _changes: &[(&str, &str)]) {
}

fn update_changes_clickable(backend: &mut dyn Backend, changes: &[(&str, &str)]) {
    backend.render(&mut |fb, stride| {
        for &(name, val) in changes {
            if name == "parameter One" {
                atlas_1().blit(fb, stride, 10, 412,
                    &format!("{:<45}", val));
            }
        }
    });
}

fn update_changes_complex(_backend: &mut dyn Backend, _changes: &[(&str, &str)]) {
}

fn update_changes_dynstat(backend: &mut dyn Backend, changes: &[(&str, &str)]) {
    backend.render(&mut |fb, stride| {
        for &(name, val) in changes {
            if name == "parameter One" {
                atlas_1().blit(fb, stride, 10, 380,
                    &format!("{:<45}", val));
            }
        }
    });
}

fn update_changes_grid(_backend: &mut dyn Backend, _changes: &[(&str, &str)]) {
}

fn update_changes_margin(_backend: &mut dyn Backend, _changes: &[(&str, &str)]) {
}

fn update_changes_pad(_backend: &mut dyn Backend, _changes: &[(&str, &str)]) {
}

fn update_changes_popup(_backend: &mut dyn Backend, _changes: &[(&str, &str)]) {
}

fn update_changes_simple(_backend: &mut dyn Backend, _changes: &[(&str, &str)]) {
}

fn update_changes_styled(_backend: &mut dyn Backend, _changes: &[(&str, &str)]) {
}

fn update_changes_substyled(_backend: &mut dyn Backend, _changes: &[(&str, &str)]) {
}

fn update_changes_unequal(_backend: &mut dyn Backend, _changes: &[(&str, &str)]) {
}

fn update_changes_widget(backend: &mut dyn Backend, changes: &[(&str, &str)]) {
    backend.render(&mut |fb, stride| {
        for &(name, val) in changes {
            if name == "parameter One" {
                atlas_1().blit(fb, stride, 10, 281,
                    &format!("{:<45}", val));
            }
        }
    });
    for &(name, val) in changes {
        if name == "parameter Two" {
            if let Ok(v) = val.parse::<f32>() {
                let v = v.clamp(0.0, 1.0);
                let filled = (790.0_f32 * v) as usize;
                if filled > 0 {
                    backend.fill_rect(5, 356, filled, 119, rgb!(255, 255, 255));
                }
                if filled < 790 {
                    backend.fill_rect(5 + filled, 356, 790 - filled, 119, rgb!(0, 0, 0));
                }
            }
        }
    }
}

