// Generated by scripts/layout.lua — do not edit.
// Re-run the transpiler to update:
//   lua scripts/layout.lua < examples/ui.lua > examples/app/ui.rs

use imgrids::{rgb, Backend, InputEvent, Renderer};
use imgrids::ttf::TtfAtlas;
use std::sync::OnceLock;

static ATLAS_1: OnceLock<TtfAtlas> = OnceLock::new();
fn atlas_1() -> &'static TtfAtlas {
    ATLAS_1.get_or_init(|| TtfAtlas::new("fonts/RobotoMono-Regular.ttf", 32, rgb!(255, 255, 255), rgb!(0, 0, 0))
        .expect("fonts/RobotoMono-Regular.ttf"))
}

static ATLAS_2: OnceLock<TtfAtlas> = OnceLock::new();
fn atlas_2() -> &'static TtfAtlas {
    ATLAS_2.get_or_init(|| TtfAtlas::new("fonts/RobotoMono-Regular.ttf", 32, rgb!(255, 255, 255), rgb!(0, 255, 0))
        .expect("fonts/RobotoMono-Regular.ttf"))
}

static ATLAS_3: OnceLock<TtfAtlas> = OnceLock::new();
fn atlas_3() -> &'static TtfAtlas {
    ATLAS_3.get_or_init(|| TtfAtlas::new("fonts/MyriadPro-Regular.ttf", 24, rgb!(255, 255, 255), rgb!(0, 255, 0))
        .expect("fonts/MyriadPro-Regular.ttf"))
}

#[derive(Clone, Copy, PartialEq)]
pub enum Menu {
    Borders,
    Clickable,
    Complex,
    DynStat,
    Grid,
    Margin,
    Pad,
    Popup,
    Simple,
    Styled,
    SubStyled,
    Unequal,
    Widget,
}

pub fn draw(backend: &mut dyn Backend, menu: Menu) {
    match menu {
        Menu::Borders => draw_borders_menu(backend),
        Menu::Clickable => draw_clickable_menu(backend),
        Menu::Complex => draw_complex_menu(backend),
        Menu::DynStat => draw_dyn_stat_menu(backend),
        Menu::Grid => draw_grid_menu(backend),
        Menu::Margin => draw_margin_menu(backend),
        Menu::Pad => draw_pad_menu(backend),
        Menu::Popup => draw_popup_menu(backend),
        Menu::Simple => draw_simple_menu(backend),
        Menu::Styled => draw_styled_menu(backend),
        Menu::SubStyled => draw_sub_styled_menu(backend),
        Menu::Unequal => draw_unequal_menu(backend),
        Menu::Widget => draw_widget_menu(backend),
    }
}

fn draw_borders_menu(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    atlas_1().draw(backend, 0, 32, "Label One");
    backend.draw_border(0, 0, 400, 96, 3, rgb!(0, 255, 0));
    atlas_1().draw(backend, 400, 32, "Label Two");
    backend.draw_border(400, 0, 400, 96, 3, rgb!(0, 255, 0));
    backend.draw_border(0, 0, 800, 96, 3, rgb!(0, 255, 0));
    atlas_1().draw(backend, 0, 128, "Label Three");
    atlas_1().draw(backend, 400, 128, "Label Four");
    backend.draw_border(400, 96, 400, 96, 2, rgb!(255, 255, 255));
    atlas_1().draw(backend, 0, 224, "Label Five");
    backend.fill_rect(0, 192, 800, 3, rgb!(255, 255, 255));
    backend.fill_rect(0, 192, 800, 3, rgb!(255, 255, 255));
    atlas_1().draw(backend, 0, 320, "Label Six");
    atlas_2().draw(backend, 0, 416, "Label Seven");
}

fn draw_clickable_menu(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    atlas_1().draw(backend, 0, 44, "Click me!");
    atlas_1().draw(backend, 0, 164, "Press me!");
    atlas_1().draw(backend, 0, 284, "Touch me!");
    backend.fill_rect(0, 360, 800, 120, rgb!(0, 0, 0));
}

fn draw_complex_menu(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    atlas_1().draw(backend, 0, 104, "Label One");
    atlas_1().draw(backend, 0, 344, "Label Two");
    atlas_1().draw(backend, 400, 64, "Label Three");
    atlas_1().draw(backend, 600, 64, "Label Four");
    atlas_1().draw(backend, 400, 224, "Label Five");
    atlas_1().draw(backend, 533, 224, "Label Six");
    atlas_1().draw(backend, 666, 224, "Label Seven");
    atlas_1().draw(backend, 400, 384, "Click!");
}

fn draw_dyn_stat_menu(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    atlas_1().draw(backend, 0, 104, "Simple Label");
    backend.fill_rect(0, 240, 800, 240, rgb!(0, 0, 0));
}

fn draw_grid_menu(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    atlas_1().draw(backend, 0, 104, "Label One");
    atlas_1().draw(backend, 400, 104, "Label Two");
    atlas_1().draw(backend, 0, 344, "Label Three");
    atlas_1().draw(backend, 400, 344, "Label Four");
}

fn draw_margin_menu(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    atlas_1().draw(backend, 15, 67, "Label One");
    atlas_1().draw(backend, 405, 67, "Label Two");
    atlas_1().draw(backend, 15, 223, "Label Three");
    atlas_1().draw(backend, 405, 223, "Label Four");
    atlas_2().draw(backend, 15, 380, "Label Five");
}

fn draw_pad_menu(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    atlas_1().draw(backend, 20, 109, "Label One");
    atlas_1().draw(backend, 400, 109, "Label Two");
    atlas_1().draw(backend, 20, 339, "Label Three");
    atlas_1().draw(backend, 400, 339, "Label Four");
}

fn draw_popup_menu(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    atlas_1().draw(backend, 200, 89, "Label One");
    atlas_1().draw(backend, 400, 89, "Label Two");
    atlas_1().draw(backend, 200, 179, "Label Three");
    atlas_1().draw(backend, 400, 179, "Label Four");
    atlas_1().draw(backend, 200, 269, "Label Five");
    atlas_1().draw(backend, 400, 269, "Label Six");
    atlas_1().draw(backend, 200, 359, "Label Seven");
    atlas_1().draw(backend, 400, 359, "Label Eight");
}

fn draw_simple_menu(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    atlas_1().draw(backend, 0, 44, "Item One");
    atlas_1().draw(backend, 0, 164, "Item Two");
    atlas_1().draw(backend, 0, 284, "Item One");
    atlas_1().draw(backend, 0, 404, "More Text");
}

fn draw_styled_menu(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    atlas_2().draw(backend, 0, 104, "Label One");
    atlas_2().draw(backend, 400, 104, "Label Two");
    atlas_2().draw(backend, 0, 344, "Label Three");
    atlas_2().draw(backend, 400, 344, "Label Four");
}

fn draw_sub_styled_menu(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    atlas_2().draw(backend, 0, 104, "Label One");
    atlas_2().draw(backend, 400, 104, "Label Two");
    atlas_3().draw(backend, 0, 348, "Label Three");
    atlas_2().draw(backend, 400, 344, "Label Four");
}

fn draw_unequal_menu(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    atlas_1().draw(backend, 0, 24, "Label One");
    atlas_1().draw(backend, 400, 24, "Label Two");
    atlas_1().draw(backend, 0, 184, "Label Three");
    atlas_1().draw(backend, 400, 184, "Label Four");
    atlas_1().draw(backend, 0, 384, "Label Five");
    atlas_1().draw(backend, 400, 384, "Label Six");
}

fn draw_widget_menu(backend: &mut dyn Backend) {
    backend.fill_rect(0, 0, 800, 480, rgb!(0, 0, 0));
    atlas_1().draw(backend, 0, 64, "Simple Label");
    backend.fill_rect(0, 160, 800, 160, rgb!(0, 0, 0));
    backend.fill_rect(0, 320, 800, 160, rgb!(0, 0, 0));
}

pub fn update(
    backend: &mut dyn Backend,
    menu: Menu,
    changes: &[(&str, &str)],
    events: &[InputEvent],
) -> Option<Menu> {
    match menu {
        Menu::Borders => update_borders_menu(backend, changes, events),
        Menu::Clickable => update_clickable_menu(backend, changes, events),
        Menu::Complex => update_complex_menu(backend, changes, events),
        Menu::DynStat => update_dyn_stat_menu(backend, changes, events),
        Menu::Grid => update_grid_menu(backend, changes, events),
        Menu::Margin => update_margin_menu(backend, changes, events),
        Menu::Pad => update_pad_menu(backend, changes, events),
        Menu::Popup => update_popup_menu(backend, changes, events),
        Menu::Simple => update_simple_menu(backend, changes, events),
        Menu::Styled => update_styled_menu(backend, changes, events),
        Menu::SubStyled => update_sub_styled_menu(backend, changes, events),
        Menu::Unequal => update_unequal_menu(backend, changes, events),
        Menu::Widget => update_widget_menu(backend, changes, events),
    }
}

fn update_borders_menu(
    backend: &mut dyn Backend,
    changes: &[(&str, &str)],
    _events: &[InputEvent],
) -> Option<Menu> {
    let _ = (backend, changes, _events);
    None
}

fn update_clickable_menu(
    backend: &mut dyn Backend,
    changes: &[(&str, &str)],
    events: &[InputEvent],
) -> Option<Menu> {
    backend.render(&mut |fb, stride| {
        for &(name, val) in changes {
            match name {
                "parameter One" => atlas_1().blit(fb, stride, 0, 404,
                    &format!("{:<47}", val)),
                _ => {}
            }
        }
    });
    for ev in events {
        if let InputEvent::Press { x, y } = ev {
            if *x < 800 && *y < 120 {
                if let Some(m) = super::function_cl(&[]) { return Some(m); }
            }
            if *x < 800 && *y >= 120 && *y < 240 {
                if let Some(m) = super::function_pr(&["hello"]) { return Some(m); }
            }
            if *x < 800 && *y >= 240 && *y < 360 {
                if let Some(m) = super::fn_multi(&["a", "b"]) { return Some(m); }
            }
            if *x < 800 && *y >= 360 && *y < 480 {
                if let Some(m) = super::fn3(&[]) { return Some(m); }
            }
        }
    }
    None
}

fn update_complex_menu(
    backend: &mut dyn Backend,
    changes: &[(&str, &str)],
    _events: &[InputEvent],
) -> Option<Menu> {
    let _ = (backend, changes, _events);
    None
}

fn update_dyn_stat_menu(
    backend: &mut dyn Backend,
    changes: &[(&str, &str)],
    _events: &[InputEvent],
) -> Option<Menu> {
    backend.render(&mut |fb, stride| {
        for &(name, val) in changes {
            match name {
                "parameter One" => atlas_1().blit(fb, stride, 0, 344,
                    &format!("{:<47}", val)),
                _ => {}
            }
        }
    });
    None
}

fn update_grid_menu(
    backend: &mut dyn Backend,
    changes: &[(&str, &str)],
    _events: &[InputEvent],
) -> Option<Menu> {
    let _ = (backend, changes, _events);
    None
}

fn update_margin_menu(
    backend: &mut dyn Backend,
    changes: &[(&str, &str)],
    _events: &[InputEvent],
) -> Option<Menu> {
    let _ = (backend, changes, _events);
    None
}

fn update_pad_menu(
    backend: &mut dyn Backend,
    changes: &[(&str, &str)],
    _events: &[InputEvent],
) -> Option<Menu> {
    let _ = (backend, changes, _events);
    None
}

fn update_popup_menu(
    backend: &mut dyn Backend,
    changes: &[(&str, &str)],
    _events: &[InputEvent],
) -> Option<Menu> {
    let _ = (backend, changes, _events);
    None
}

fn update_simple_menu(
    backend: &mut dyn Backend,
    changes: &[(&str, &str)],
    _events: &[InputEvent],
) -> Option<Menu> {
    let _ = (backend, changes, _events);
    None
}

fn update_styled_menu(
    backend: &mut dyn Backend,
    changes: &[(&str, &str)],
    _events: &[InputEvent],
) -> Option<Menu> {
    let _ = (backend, changes, _events);
    None
}

fn update_sub_styled_menu(
    backend: &mut dyn Backend,
    changes: &[(&str, &str)],
    _events: &[InputEvent],
) -> Option<Menu> {
    let _ = (backend, changes, _events);
    None
}

fn update_unequal_menu(
    backend: &mut dyn Backend,
    changes: &[(&str, &str)],
    _events: &[InputEvent],
) -> Option<Menu> {
    let _ = (backend, changes, _events);
    None
}

fn update_widget_menu(
    backend: &mut dyn Backend,
    changes: &[(&str, &str)],
    _events: &[InputEvent],
) -> Option<Menu> {
    backend.render(&mut |fb, stride| {
        for &(name, val) in changes {
            match name {
                "parameter One" => atlas_1().blit(fb, stride, 0, 224,
                    &format!("{:<47}", val)),
                _ => {}
            }
        }
    });
    for &(name, val) in changes {
        if name == "parameter Two" {
            if let Ok(v) = val.parse::<f32>() {
                let v = v.clamp(0.0, 1.0);
                let filled = (800_usize as f32 * v) as usize;
                if filled > 0 {
                    backend.fill_rect(0, 320, filled, 160, rgb!(255, 255, 255));
                }
                if filled < 800 {
                    backend.fill_rect(0 + filled, 320, 800 - filled, 160, rgb!(0, 0, 0));
                }
            }
        }
    }
    None
}

